const R = require("../node_modules/ramda/dist/ramda.js");

const Person = require("./Person.js");
const Series = require("./Series.js");
const SeriesEntry = require("./SeriesEntry.js");

const Book = {
  _206_BONES: "_206Bones",
  _61_HOURS: "_61Hours",
  A_CHRISTMAS_PARTY: "aChristmasParty",
  A_FATAL_INVERSION: "aFatalInversion",
  A_HIGHLAND_CHRISTMAS: "aHighlandChristmas",
  A_MAN_LAY_DEAD: "aManLayDead",
  AND_THEN_THERE_WERE_NONE: "andThenThereWereNone",
  A_PLAGUE_OF_SECRETS: "aPlagueOfSecrets",
  A_SIMPLE_PLAN: "aSimplePlan",
  A_STUDY_IN_SCARLET: "aStudyInScarlet",
  A_TAP_ON_THE_WINDOW: "aTapOnTheWindow",
  A_TEST_OF_WILLS: "aTestOfWills",
  A_TOAST_TO_MURDER: "aToastToMurder",
  A_WANTED_MAN: "aWantedMan",
  BLOOD_ON_SNOW: "bloodOnSnow",
  BLOOD_ON_THE_TRACKS: "bloodOnTheTracks",
  BRING_ME_BACK: "bringMeBack",
  BROADCHURCH: "broadchurch",
  BROKEN: "broken",
  CAMINO_WINDS: "caminoWinds",
  CAUGHT: "caught",
  CHASING_DARKNESS: "chasingDarkness",
  CRAZY_LOVE_YOU: "crazyLoveYou",
  CRIME_AT_CHRISTMAS: "crimeAtChristmas",
  CRIME_SCENE: "crimeScene",
  DARK_HARBOR: "darkHarbor",
  DARKLY_DREAMING_DEXTER: "darklyDreamingDexter",
  DARK_OF_THE_MOON: "darkOfTheMoon",
  DARK_PLACES: "darkPlaces",
  DARK_SACRED_NIGHT: "darkSacredNight",
  DEARLY_DEVOTED_DEXTER: "dearlyDevotedDexter",
  DEATHTRAP: "deathtrap",
  DEFENDING_JACOB: "defendingJacob",
  DEXTER_BY_DESIGN: "dexterByDesign",
  DEXTER_IN_THE_DARK: "dexterInTheDark",
  DEXTER_IS_DEAD: "dexterIsDead",
  DEXTER_IS_DELICIOUS: "dexterIsDelicious",
  DEXTERS_FINAL_CUT: "dextersFinalCut",
  DIRTY_BLONDE: "dirtyBlonde",
  DIVINE_JUSTICE: "divineJustice",
  DONT_BLINK: "dontBlink",
  DOUBLE_DEXTER: "doubleDexter",
  DOUBLE_INDEMNITY: "doubleIndemnity",
  EIGHT_PERFECT_MURDERS: "eightPerfectMurders",
  EVERY_LAST_LIE: "everyLastLie",
  EVIL_AT_HEART: "evilAtHeart",
  FOOL_ME_ONCE: "foolMeOnce",
  FORCE_OF_NATURE_2012: "forceOfNature2012",
  FORCE_OF_NATURE_2018: "forceOfNature2018",
  GHOSTMAN: "ghostman",
  GONE_GIRL: "goneGirl",
  HEARTSICK: "heartsick",
  HEAT_LIGHTNING: "heatLightning",
  HELLBENT: "hellbent",
  HELLS_CORNER: "hellsCorner",
  HERCULE_POIROTS_CHRISTMAS: "herculePoirotsChristmas",
  HIDDEN_BODIES: "hiddenBodies",
  HOME: "home",
  ICE_COLD: "iceCold",
  ID_KNOW_YOU_ANYWHERE: "idKnowYouAnywhere",
  I_HEARD_YOU_PAINT_HOUSES: "iHeardYouPaintHouses",
  I_KNOW_A_SECRET: "iKnowASecret",
  IN_A_DARK_DARK_WOOD: "inADarkDarkWood",
  INK_AND_BONE: "inkAndBone",
  IN_THE_BLOOD: "inTheBlood",
  IRON_HOUSE: "ironHouse",
  I_SEE_YOU: "iSeeYou",
  KILL_FEE: "killFee",
  KILL_YOU_TWICE: "killYouTwice",
  LETHAL_WHITE: "lethalWhite",
  LET_ME_GO: "letMeGo",
  LIARS_LULLABY: "liarsLullaby",
  LIFE_SENTENCES: "lifeSentences",
  LIVE_BY_NIGHT: "liveByNight",
  LOVE_KILLS: "loveKills",
  LUCKY_JIM: "luckyJim",
  MAGPIE_MURDERS: "magpieMurders",
  MAKE_ME: "makeMe",
  MALICE: "malice",
  MALICE_AFORETHOUGHT: "maliceAforethought",
  MARKED_FOR_LIFE: "markedForLife",
  MEAN_STREAK: "meanStreak",
  MISSING_YOU: "missingYou",
  MURDER_ON_THE_ORIENT_EXPRESS: "murderOnTheOrientExpress",
  MYSTERY: "mystery",
  NEVER_GO_BACK: "neverGoBack",
  NEW_TRICKS: "newTricks",
  NINE_PERFECT_STRANGERS: "ninePerfectStrangers",
  NOTHING_TO_LOSE: "nothingToLose",
  ODD_THOMAS: "oddThomas",
  ONE_GOOD_TURN: "oneGoodTurn",
  ONE_KICK: "oneKick",
  ONE_SHOT: "oneShot",
  ORPHAN_X: "orphanX",
  PERSONAL: "personal",
  PHANTOM: "phantom",
  PIECES_OF_HER: "piecesOfHer",
  RECONSTRUCTING_AMELIA: "reconstructingAmelia",
  REDEMPTION_ROAD: "redemptionRoad",
  SHARP_OBJECTS: "sharpObjects",
  SHE_WHO_WAS_NO_MORE: "sheWhoWasNoMore",
  SIX_YEARS: "sixYears",
  STAY_CLOSE: "stayClose",
  STILL_LIFE: "stillLife",
  STONE_COLD_2007: "stoneCold2007",
  STONE_COLD_2014: "stoneCold2014",
  STRANGERS_ON_A_TRAIN: "strangersOnATrain",
  SUSPECT: "suspect",
  SWEETHEART: "sweetheart",
  SWEET_LITTLE_LIES: "sweetLittleLies",
  SYCAMORE_ROW: "sycamoreRow",
  THAT_NIGHT: "thatNight",
  THE_ABC_MURDERS: "theAbcMurders",
  THE_AX: "theAx",
  THE_BLACK_ECHO: "theBlackEcho",
  THE_BLACK_WIDOW: "theBlackWidow",
  THE_BONE_PARADE: "theBoneParade",
  THE_BRASS_VERDICT: "theBrassVerdict",
  THE_BRIDE_COLLECTOR: "theBrideCollector",
  THE_BROKEN_WINDOW: "theBrokenWindow",
  THE_BRUTAL_TELLING: "theBrutalTelling",
  THE_CAMEL_CLUB: "theCamelClub",
  THE_CHRISTMAS_CRIMES_AT_PUZZEL_MANOR: "theChristmasCrimesAtPuzzelManor",
  THE_COLLECTORS: "theCollectors",
  THE_COUPLE_NEXT_DOOR: "theCoupleNextDoor",
  THE_CROSSING: "theCrossing",
  THE_DEATH_OF_MRS_WESTAWAY: "theDeathOfMrsWestaway",
  THE_DEPARTMENT_OF_SENSITIVE_CRIMES: "theDepartmentOfSensitiveCrimes",
  THE_DROWNER: "theDrowner",
  THE_DRY: "theDry",
  THE_ENGLISH_SPY: "theEnglishSpy",
  THE_ESCAPE_ROOM: "theEscapeRoom",
  THE_EXPATS: "theExpats",
  THE_FALLEN: "theFallen",
  THE_FAMILY_UPSTAIRS: "theFamilyUpstairs",
  THE_FIFTH_WITNESS: "theFifthWitness",
  THE_FINAL_SOLUTION: "theFinalSolution",
  THE_GIRL_WHO_KICKED_THE_HORNETS_NEST: "theGirlWhoKickedTheHornetsNest",
  THE_GIRL_WHO_PLAYED_WITH_FIRE: "theGirlWhoPlayedWithFire",
  THE_GIRL_WITH_THE_DRAGON_TATTOO: "theGirlWithTheDragonTattoo",
  THE_GODS_OF_GUILT: "theGodsOfGuilt",
  THE_GREEK_COFFIN_MYSTERY: "theGreekCoffinMystery",
  THE_GUILTY: "theGuilty",
  THE_HEIST: "theHeist",
  THE_HOUND_OF_THE_BASKERVILLES: "theHoundOfTheBaskervilles",
  THE_HUNT_CLUB: "theHuntClub",
  THE_HUSH: "theHush",
  THE_INNOCENT_MAN: "theInnocentMan",
  THE_KEEPSAKE: "theKeepsake",
  THE_KILLER_NEXT_DOOR: "theKillerNextDoor",
  THE_KILLINGS_AT_BADGERS_DRIFT: "theKillingsAtBadgersDrift",
  THE_LAST_CHILD: "theLastChild",
  THE_LAST_PAINTING_OF_SARA_DE_VOS: "theLastPaintingOfSaraDeVos",
  THE_LATE_SHOW: "theLateShow",
  THE_LEOPARD: "theLeopard",
  THE_LINCOLN_LAWYER: "theLincolnLawyer",
  THE_LOST_MAN: "theLostMan",
  THE_MOST_DANGEROUS_THING: "theMostDangerousThing",
  THE_MYSTERIOUS_AFFAIR_AT_STYLES: "theMysteriousAffairAtStyles",
  THE_NARROWS: "theNarrows",
  THE_NIGHT_SEASON: "theNightSeason",
  THE_NOWHERE_MAN: "theNowhereMan",
  THE_PALLBEARERS: "thePallbearers",
  THE_PROGRAM: "theProgram",
  THE_PROMISE: "thePromise",
  THE_RED_HOUSE_MYSTERY: "theRedHouseMystery",
  THE_REMBRANDT_AFFAIR: "theRembrandtAffair",
  THE_REVERSAL: "theReversal",
  THE_SANTA_KLAUS_MURDER: "theSantaKlausMurder",
  THE_SECRET_HISTORY: "theSecretHistory",
  THE_SHADOW_TRACER: "theShadowTracer",
  THE_SILENT_PATIENT: "theSilentPatient",
  THE_SNOWMAN: "theSnowman",
  THE_STRANGER: "theStranger",
  THE_STUPIDEST_ANGEL: "theStupidestAngel",
  THE_SWEETNESS_AT_THE_BOTTOM_OF_THE_PIE: "theSweetnessAtTheBottomOfThePie",
  THE_THIN_MAN: "theThinMan",
  THE_TRAVELERS: "theTravelers",
  THE_TURN_OF_THE_KEY: "theTurnOfTheKey",
  THE_TWO_MINUTE_RULE: "theTwoMinuteRule",
  THE_WATCHMAN: "theWatchman",
  THE_WITCH_ELM: "theWitchElm",
  THE_WOMAN_IN_CABIN_10: "theWomanInCabin10",
  THE_WOMAN_IN_THE_WINDOW: "theWomanInTheWindow",
  THE_WOODS: "theWoods",
  THE_WORD_IS_MURDER: "theWordIsMurder",
  THE_WRONG_SIDE_OF_GOODBYE: "theWrongSideOfGoodbye",
  TRAIL_OF_BLOOD: "trailOfBlood",
  TRIP_TYCH: "tripTych",
  TRUE_EVIL: "trueEvil",
  TWO_KINDS_OF_TRUTH: "twoKindsOfTruth",
  UNDER_MY_SKIN: "underMySkin",
  VANISHING_GAMES: "vanishingGames",
  VERTIGO: "vertigo",
  VICTIMS: "victims",
  WAITING_FOR_WEDNESDAY: "waitingForWednesday",
  WHAT_THE_DEAD_KNOW: "whatTheDeadKnow",
  WHEN_THE_WIND_BLOWS: "whenTheWindBlows",
  WHERE_THE_CRAWDADS_SING: "whereTheCrawdadsSing",
  WHISPERS_OF_THE_DEAD: "whispersOfTheDead",
  WICKED_PREY: "wickedPrey",
  YOU: "you",

  properties: {
    _206Bones: {
      title: "206 Bones",
      authorKeys: [Person.KATHY_REICHS],
      series: [SeriesEntry.create(Series.TEMPERANCE_BRENNAN, 12)],
      meeting: "2010.04.26",
      dcl: "911690114",
    },
    _61Hours: {
      title: "61 Hours",
      authorKeys: [Person.LEE_CHILD],
      series: [SeriesEntry.create(Series.JACK_REACHER, 14)],
      meeting: "2011.03.28",
      dcl: "946941114",
    },
    aChristmasParty: {
      title: "A Christmas Party",
      authorKeys: [Person.GEORGETTE_HEYER],
      meeting: "2017.12.15",
      dcl: "1444035114",
    },
    aFatalInversion: {
      title: "A Fatal Inversion",
      authorKeys: [Person.BARBARA_VINE],
      series: [SeriesEntry.create(Series.PETER_SWANSON_SUGGESTS, 6)],
      gr: "book/show/420967.A_Fatal_Inversion",
      lt: "work/170886",
    },
    aHighlandChristmas: {
      title: "A Highland Christmas",
      authorKeys: [Person.MC_BEATON],
      series: [SeriesEntry.create(Series.HAMISH_MACBETH, 16)],
      meeting: "2008.12.22",
      dcl: "1084060114",
    },
    aManLayDead: {
      title: "A Man Lay Dead",
      authorKeys: [Person.NGAIO_MARSH],
      series: [SeriesEntry.create(Series.RODERICK_ALLEYN, 1)],
      meeting: "2015.12.17",
      dcl: "1294793114",
    },
    andThenThereWereNone: {
      title: "And Then There Were None",
      authorKeys: [Person.AGATHA_CHRISTIE],
      meeting: "2014.12.18",
      dcl: "1063049114",
    },
    aPlagueOfSecrets: {
      title: "A Plague of Secrets",
      authorKeys: [Person.JOHN_LESCROART],
      series: [SeriesEntry.create(Series.DISMAS_HARDY, 11)],
      meeting: "2010.02.22",
      dcl: "908384114",
    },
    aSimplePlan: {
      title: "A Simple Plan",
      authorKeys: [Person.SCOTT_B_SMITH],
      series: [SeriesEntry.create(Series.PETER_SWANSON_SUGGESTS, 8)],
      dcl: "1514573114",
      gr: "book/show/21727.A_Simple_Plan",
      lt: "work/150141",
    },
    aStudyInScarlet: {
      title: "A Study in Scarlet",
      authorKeys: [Person.ARTHUR_CONAN_DOYLE],
      series: [SeriesEntry.create(Series.SHERLOCK_HOLMES, 1)],
      meeting: "2012.02.27",
      dcl: "1250653114",
    },
    aTapOnTheWindow: {
      title: "A Tap on the Window",
      authorKeys: [Person.LINWOOD_BARCLAY],
      meeting: "2014.04.28",
      dcl: "1153565114",
    },
    aTestOfWills: {
      title: "A Test of Wills",
      authorKeys: [Person.CHARLES_TODD],
      meeting: "2007.04.23",
      dcl: "1228464114",
    },
    aToastToMurder: {
      title: "A Toast to Murder",
      authorKeys: [Person.MICHELE_SCOTT],
      series: [SeriesEntry.create(Series.WINE_LOVERS_MYSTERIES, 6)],
      meeting: "2010.07.26",
      lt: "work/9739948",
    },
    aWantedMan: {
      title: "A Wanted Man",
      authorKeys: [Person.LEE_CHILD],
      series: [SeriesEntry.create(Series.JACK_REACHER, 17)],
      meeting: "2014.03.24",
      dcl: "1054861114",
    },
    bloodOnSnow: {
      title: "Blood On Snow",
      authorKeys: [Person.JO_NESBO],
      meeting: "2016.01.25",
      dcl: "1251107114",
    },
    bloodOnTheTracks: {
      title: "Blood on the Tracks",
      authorKeys: [Person.BARBARA_NICKLESS],
      series: [
        SeriesEntry.create(Series.SYDNEY_ROSE_PARNELL, 1),
        SeriesEntry.create(Series.GAIL_H_SUGGESTS, 2),
      ],
      dcl: "1359332114",
      lt: "work/18319544",
    },
    bringMeBack: {
      title: "Bring Me Back",
      authorKeys: [Person.BA_PARIS],
      dcl: "1446735114",
      lt: "work/20629560",
      meeting: "2019.02.25",
    },
    broadchurch: {
      title: "Broadchurch",
      authorKeys: [Person.ERIN_KELLY, Person.CHRIS_CHIBNALL],
      series: [SeriesEntry.create(Series.BROADCHURCH, 1)],
      gr: "book/show/19561890-broadchurch",
      lt: "work/14809117",
    },
    broken: {
      title: "Broken",
      authorKeys: [Person.KARIN_SLAUGHTER],
      series: [SeriesEntry.create(Series.GEORGIA, 2)],
      meeting: "2011.10.24",
      dcl: "952803114",
    },
    caminoWinds: {
      title: "Camino Winds",
      authorKeys: [Person.JOHN_GRISHAM],
      series: [SeriesEntry.create(Series.CAMINO_ISLAND, 2)],
      dcl: "1636922114",
      lt: "work/24158942",
      meeting: "2020.09.28",
    },
    caught: {
      title: "Caught",
      authorKeys: [Person.HARLAN_COBEN],
      meeting: "2011.02.28",
      dcl: "938415114",
    },
    chasingDarkness: {
      title: "Chasing Darkness",
      authorKeys: [Person.ROBERT_CRAIS],
      series: [SeriesEntry.create(Series.ELVIS_COLE, 12)],
      meeting: "2013.05.20",
      dcl: "861205114",
    },
    crazyLoveYou: {
      title: "Crazy Love You",
      authorKeys: [Person.LISA_UNGER],
      meeting: "2016.02.22",
      dcl: "1251088114",
    },
    crimeAtChristmas: {
      title: "Crime at Christmas",
      authorKeys: [Person.CHB_KITCHIN],
      series: [SeriesEntry.create(Series.MALCOLM_WARREN, 2)],
      lt: "work/997859",
      meeting: "2020.12.18",
    },
    crimeScene: {
      title: "Crime Scene",
      authorKeys: [Person.JONATHAN_KELLERMAN, Person.JESSE_KELLERMAN],
      series: [SeriesEntry.create(Series.CLAY_EDISON, 1)],
      meeting: "2018.05.21",
      dcl: "1407385114",
      lt: "work/18796542",
    },
    darkHarbor: {
      title: "Dark Harbor",
      authorKeys: [Person.STUART_WOODS],
      series: [SeriesEntry.create(Series.STONE_BARRINGTON, 12)],
      meeting: "2009.06.22",
      dcl: "741038114",
    },
    darklyDreamingDexter: {
      title: "Darkly Dreaming Dexter",
      authorKeys: [Person.JEFF_LINDSAY],
      series: [SeriesEntry.create(Series.DEXTER, 1)],
      meeting: "2007.02.26",
      dcl: "656271114",
      lt: "work/93729",
    },
    darkOfTheMoon: {
      title: "Dark of the Moon",
      authorKeys: [Person.JOHN_SANDFORD],
      series: [SeriesEntry.create(Series.VIRGIL_FLOWERS, 1)],
      meeting: "2011.08.22",
      dcl: "825315114",
    },
    darkPlaces: {
      title: "Dark Places",
      authorKeys: [Person.GILLIAN_FLYNN],
      meeting: "2010.09.27",
      dcl: "906965114",
    },
    darkSacredNight: {
      title: "Dark Sacred Night",
      authorKeys: [Person.MICHAEL_CONNELLY],
      series: [
        SeriesEntry.create(Series.RENEE_BALLARD, 2),
        SeriesEntry.create(Series.HARRY_BOSCH, 21),
      ],
      dcl: "1475392114",
      lt: "work/21016230",
      meeting: "2019.06.24",
    },
    dearlyDevotedDexter: {
      title: "Dearly Devoted Dexter",
      authorKeys: [Person.JEFF_LINDSAY],
      series: [SeriesEntry.create(Series.DEXTER, 2)],
      meeting: "2008.02.25",
      dcl: "700955114",
    },
    deathtrap: {
      title: "Deathtrap",
      authorKeys: [Person.IRA_LEVIN],
      series: [SeriesEntry.create(Series.PERFECT_MURDERS_LIST, 7)],
      lt: "work/124068",
    },
    defendingJacob: {
      title: "Defending Jacob",
      authorKeys: [Person.WILLIAM_LANDAY],
      meeting: "2013.06.24",
      dcl: "1021979114",
    },
    dexterByDesign: {
      title: "Dexter by Design",
      authorKeys: [Person.JEFF_LINDSAY],
      series: [SeriesEntry.create(Series.DEXTER, 4)],
      meeting: "2011.04.25",
      dcl: "925270114",
    },
    dexterInTheDark: {
      title: "Dexter in the Dark",
      authorKeys: [Person.JEFF_LINDSAY],
      series: [SeriesEntry.create(Series.DEXTER, 3)],
      dcl: "811845114",
      lt: "work/1715003",
    },
    dexterIsDead: {
      title: "Dexter is Dead",
      authorKeys: [Person.JEFF_LINDSAY],
      series: [SeriesEntry.create(Series.DEXTER, 8)],
      lt: "work/15687387",
    },
    dexterIsDelicious: {
      title: "Dexter is Delicious",
      authorKeys: [Person.JEFF_LINDSAY],
      series: [SeriesEntry.create(Series.DEXTER, 5)],
      meeting: "2012.05.29",
      dcl: "956551114",
    },
    dextersFinalCut: {
      title: "Dexter's Final Cut",
      authorKeys: [Person.JEFF_LINDSAY],
      series: [SeriesEntry.create(Series.DEXTER, 7)],
      lt: "work/13629497",
    },
    dirtyBlonde: {
      title: "Dirty Blonde",
      authorKeys: [Person.LISA_SCOTTOLINE],
      meeting: "2008.03.24",
      dcl: "742156114",
    },
    divineJustice: {
      title: "Divine Justice",
      authorKeys: [Person.DAVID_BALDACCI],
      series: [SeriesEntry.create(Series.THE_CAMEL_CLUB, 4)],
      lt: "work/5874884",
      wiki: "Divine_Justice_(novel)",
    },
    dontBlink: {
      title: "Don't Blink",
      authorKeys: [Person.JAMES_PATTERSON],
      meeting: "2011.11.28",
      dcl: "959886114",
    },
    doubleDexter: {
      title: "Double Dexter",
      authorKeys: [Person.JEFF_LINDSAY],
      series: [SeriesEntry.create(Series.DEXTER, 6)],
      lt: "work/10844880",
    },
    doubleIndemnity: {
      title: "Double Indemnity",
      authorKeys: [Person.JAMES_M_CAIN],
      series: [SeriesEntry.create(Series.PERFECT_MURDERS_LIST, 4)],
      lt: "work/5222842",
    },
    eightPerfectMurders: {
      title: "Eight Perfect Murders",
      authorKeys: [Person.PETER_SWANSON],
      dcl: "1615636114",
      lt: "work/23575042",
      meeting: "2020.06.22",
    },
    everyLastLie: {
      title: "Every Last Lie",
      authorKeys: [Person.MARY_KUBICA],
      meeting: "2018.01.22",
      dcl: "1387222114",
      lt: "work/19062304",
    },
    evilAtHeart: {
      title: "Evil at Heart",
      authorKeys: [Person.CHELSEA_CAIN],
      series: [SeriesEntry.create(Series.GRETCHEN_LOWELL, 3)],
      lt: "work/8101893",
    },
    foolMeOnce: {
      title: "Fool Me Once",
      authorKeys: [Person.HARLAN_COBEN],
      dcl: "1300151114",
      meeting: "2017.02.27",
    },
    forceOfNature2012: {
      title: "Force of Nature (2012)",
      authorKeys: [Person.CJ_BOX],
      series: [SeriesEntry.create(Series.JOE_PICKETT, 12)],
      meeting: "2012.11.26",
      dcl: "1022393114",
    },
    forceOfNature2018: {
      title: "Force of Nature (2018)",
      authorKeys: [Person.JANE_HARPER],
      series: [SeriesEntry.create(Series.AARON_FALK, 2)],
      dcl: "1430689114",
      lt: "work/19768930",
      meeting: "2020.01.27",
    },
    ghostman: {
      title: "Ghostman",
      authorKeys: [Person.ROGER_HOBBS],
      series: [SeriesEntry.create(Series.GHOSTMAN, 1)],
      meeting: "2014.07.28",
      dcl: "1218653114",
    },
    goneGirl: {
      title: "Gone Girl",
      authorKeys: [Person.GILLIAN_FLYNN],
      dcl: "1033248114",
      lt: "work/11234211",
    },
    heartsick: {
      title: "Heartsick",
      authorKeys: [Person.CHELSEA_CAIN],
      series: [SeriesEntry.create(Series.GRETCHEN_LOWELL, 1)],
      meeting: "2008.05.26",
      dcl: "816231114",
    },
    heatLightning: {
      title: "Heat Lightning",
      authorKeys: [Person.JOHN_SANDFORD],
      series: [SeriesEntry.create(Series.VIRGIL_FLOWERS, 2)],
      meeting: "2012.04.23",
      dcl: "868270114",
    },
    hellbent: {
      title: "Hellbent",
      authorKeys: [Person.GREGG_HURWITZ],
      series: [SeriesEntry.create(Series.EVAN_SMOAK, 3)],
      meeting: "2018.06.25",
      dcl: "1431233114",
    },
    hellsCorner: {
      title: "Hell's Corner",
      authorKeys: [Person.DAVID_BALDACCI],
      series: [SeriesEntry.create(Series.THE_CAMEL_CLUB, 5)],
      lt: "work/9768778",
      wiki: "Hell%27s_Corner",
    },
    herculePoirotsChristmas: {
      title: "Hercule Poirot's Christmas",
      authorKeys: [Person.AGATHA_CHRISTIE],
      series: [SeriesEntry.create(Series.HERCULE_POIROT, 19)],
      meeting: "2010.12.27",
      dcl: "975256114",
    },
    hiddenBodies: {
      title: "Hidden Bodies",
      authorKeys: [Person.CAROLINE_KEPNES],
      series: [
        SeriesEntry.create(Series.YOU, 2),
        SeriesEntry.create(Series.PETER_SWANSON_SUGGESTS, 5),
      ],
      dcl: "1273599114",
      gr: "book/show/29430824-hidden-bodies",
      lt: "work/15737078",
    },
    home: {
      title: "Home",
      authorKeys: [Person.HARLAN_COBEN],
      series: [SeriesEntry.create(Series.MYRON_BOLITAR, 11)],
      meeting: "2017.10.23",
      dcl: "1330605114",
    },
    iceCold: {
      title: "Ice Cold",
      authorKeys: [Person.TESS_GERRITSEN],
      series: [SeriesEntry.create(Series.RIZZOLI_AND_ISLES, 8)],
      meeting: "2010.11.22",
      dcl: "1450069114",
    },
    idKnowYouAnywhere: {
      title: "I'd Know You Anywhere",
      authorKeys: [Person.LAURA_LIPPMAN],
      meeting: "2012.01.23",
      dcl: "959899114",
    },
    iHeardYouPaintHouses: {
      title: "I Heard You Paint Houses",
      authorKeys: [Person.CHARLES_BRANDT],
      gr: "book/show/934378.I_Heard_You_Paint_Houses",
      lt: "work/154023",
    },
    iKnowASecret: {
      title: "I Know a Secret",
      authorKeys: [Person.TESS_GERRITSEN],
      series: [SeriesEntry.create(Series.RIZZOLI_AND_ISLES, 12)],
      meeting: "2018.07.23",
      dcl: "1407387114",
    },
    inADarkDarkWood: {
      title: "In a Dark, Dark Wood",
      authorKeys: [Person.RUTH_WARE],
      meeting: "2017.08.28",
      dcl: "1278756114",
    },
    inkAndBone: {
      title: "Ink & Bone",
      authorKeys: [Person.LISA_UNGER],
      meeting: "2016.12.15",
      dcl: "1578361114",
    },
    inTheBlood: {
      title: "In The Blood",
      authorKeys: [Person.LISA_UNGER],
      meeting: "2015.05.18",
      dcl: "1176076114",
    },
    ironHouse: {
      title: "Iron House",
      authorKeys: [Person.JOHN_HART],
      meeting: "2013.08.26",
      dcl: "993819114",
    },
    iSeeYou: {
      title: "I See You",
      authorKeys: [Person.CLARE_MACKINTOSH],
      meeting: "2018.02.26",
      dcl: "1384268114",
    },
    killFee: {
      title: "Kill Fee",
      authorKeys: [Person.OWEN_LAUKKANEN],
      series: [SeriesEntry.create(Series.STEVENS_AND_WINDERMERE, 3)],
      meeting: "2015.04.27",
      dcl: "1180980114",
    },
    killYouTwice: {
      title: "Kill You Twice",
      authorKeys: [Person.CHELSEA_CAIN],
      series: [SeriesEntry.create(Series.GRETCHEN_LOWELL, 5)],
      lt: "work/12244209",
    },
    lethalWhite: {
      title: "Lethal White",
      authorKeys: [Person.ROBERT_GALBRAITH],
      series: [SeriesEntry.create(Series.CORMORAN_STRIKE, 4)],
      dcl: "1493220114",
      lt: "work/17525753",
      meeting: "2019.10.28",
    },
    letMeGo: {
      title: "Let Me Go",
      authorKeys: [Person.CHELSEA_CAIN],
      series: [SeriesEntry.create(Series.GRETCHEN_LOWELL, 6)],
      lt: "work/13216528",
    },
    liarsLullaby: {
      title: "Liar's Lullaby",
      authorKeys: [Person.MEG_GARDINER],
      series: [SeriesEntry.create(Series.JO_BECKETT, 3)],
      meeting: "2011.06.27",
      dcl: "955448114",
      lt: "work/9209696",
    },
    lifeSentences: {
      title: "Life Sentences",
      authorKeys: [Person.ALICE_BLANCHARD],
      meeting: "2008.11.24",
      lt: "work/1359460",
    },
    liveByNight: {
      title: "Live by Night",
      authorKeys: [Person.DENNIS_LEHANE],
      series: [SeriesEntry.create(Series.JOE_COUGHLIN, 2)],
      meeting: "2014.06.23",
      dcl: "1060297114",
    },
    loveKills: {
      title: "Love Kills",
      authorKeys: [Person.EDNA_BUCHANAN],
      meeting: "2008.08.25",
      dcl: "849764114",
    },
    luckyJim: {
      title: "Lucky Jim",
      authorKeys: [Person.KINGSLEY_AMIS],
      series: [SeriesEntry.create(Series.PETER_SWANSON_SUGGESTS, 7)],
      dcl: "1463493114",
      gr: "book/show/395182.Lucky_Jim",
      lt: "work/7166",
    },
    magpieMurders: {
      title: "Magpie Murders",
      authorKeys: [Person.ANTHONY_HOROWITZ],
      meeting: "2018.09.24",
      dcl: "1387233114",
    },
    makeMe: {
      title: "Make Me",
      authorKeys: [Person.LEE_CHILD],
      series: [SeriesEntry.create(Series.JACK_REACHER, 20)],
      meeting: "2016.06.27",
      dcl: "1311811114",
    },
    malice: {
      title: "Malice",
      authorKeys: [Person.LISA_JACKSON],
      meeting: "2009.10.26",
      dcl: "1084081114",
    },
    maliceAforethought: {
      title: "Malice Aforethought",
      authorKeys: [Person.ANTHONY_BERKELEY_COX],
      series: [SeriesEntry.create(Series.PERFECT_MURDERS_LIST, 2)],
      lt: "work/247583",
    },
    markedForLife: {
      title: "Marked for Life",
      authorKeys: [Person.EMELIE_SCHEPP],
      series: [SeriesEntry.create(Series.JANA_BERZELIUS, 1)],
      meeting: "2017.03.27",
      dcl: "1329705114",
      lt: "work/15863615",
    },
    meanStreak: {
      title: "Mean Streak",
      authorKeys: [Person.SANDRA_BROWN],
      meeting: "2015.01.26",
      dcl: "1215092114",
    },
    missingYou: {
      title: "Missing You",
      authorKeys: [Person.HARLAN_COBEN],
      meeting: "2014.10.27",
      dcl: "1615407114",
    },
    murderOnTheOrientExpress: {
      title: "Murder on the Orient Express",
      authorKeys: [Person.AGATHA_CHRISTIE],
      series: [SeriesEntry.create(Series.HERCULE_POIROT, 10)],
      dcl: "792491114",
      lt: "work/2742",
    },
    mystery: {
      title: "Mystery",
      authorKeys: [Person.JONATHAN_KELLERMAN],
      series: [SeriesEntry.create(Series.ALEX_DELAWARE, 26)],
      meeting: "2011.12.12",
      dcl: "1615417114",
    },
    neverGoBack: {
      title: "Never Go Back",
      authorKeys: [Person.LEE_CHILD],
      series: [SeriesEntry.create(Series.JACK_REACHER, 18)],
      dcl: "1137507114",
      lt: "work/13480915",
    },
    newTricks: {
      title: "New Tricks",
      authorKeys: [Person.DAVID_ROSENFELT],
      series: [SeriesEntry.create(Series.ANDY_CARPENTER, 7)],
      meeting: "2010.05.24",
      dcl: "919355114",
    },
    ninePerfectStrangers: {
      title: "Nine Perfect Strangers",
      authorKeys: [Person.LIANE_MORIARTY],
      dcl: "1518027114",
      lt: "work/21901086",
      meeting: "2020.10.26",
    },
    nothingToLose: {
      title: "Nothing to Lose",
      authorKeys: [Person.LEE_CHILD],
      series: [SeriesEntry.create(Series.JACK_REACHER, 12)],
      meeting: "2009.09.28",
      dcl: "849387114",
    },
    oddThomas: {
      title: "Odd Thomas",
      authorKeys: [Person.DEAN_KOONTZ],
      series: [SeriesEntry.create(Series.ODD_THOMAS, 1)],
      meeting: "2007.07.23",
      dcl: "1231369114",
    },
    oneGoodTurn: {
      title: "One Good Turn",
      authorKeys: [Person.KATE_ATKINSON],
      meeting: "2008.10.27",
      dcl: "1554992114",
    },
    oneKick: {
      title: "One Kick",
      authorKeys: [Person.CHELSEA_CAIN],
      series: [SeriesEntry.create(Series.KICK_LANNIGAN, 1)],
      meeting: "2015.07.27",
      dcl: "1211996114",
    },
    oneShot: {
      title: "One Shot",
      authorKeys: [Person.LEE_CHILD],
      series: [SeriesEntry.create(Series.JACK_REACHER, 9)],
      meeting: "2009.03.23",
      dcl: "962840114",
      lt: "work/156525",
    },
    orphanX: {
      title: "Orphan X",
      authorKeys: [Person.GREGG_HURWITZ],
      series: [SeriesEntry.create(Series.EVAN_SMOAK, 1)],
      meeting: "2017.05.22",
      dcl: "1613028114",
    },
    personal: {
      title: "Personal",
      authorKeys: [Person.LEE_CHILD],
      series: [SeriesEntry.create(Series.JACK_REACHER, 19)],
      meeting: "2015.08.24",
      dcl: "1381470114",
    },
    phantom: {
      title: "Phantom",
      authorKeys: [Person.JO_NESBO],
      series: [SeriesEntry.create(Series.HARRY_HOLE, 9)],
      meeting: "2013.11.25",
      dcl: "1061473114",
    },
    piecesOfHer: {
      title: "Pieces of Her",
      authorKeys: [Person.KARIN_SLAUGHTER],
      dcl: "1460952114",
      lt: "work/20847841",
      meeting: "2019.07.22",
    },
    reconstructingAmelia: {
      title: "Reconstructing Amelia",
      authorKeys: [Person.KIMBERLY_MCCREIGHT],
      meeting: "2015.03.23",
      dcl: "1093239114",
    },
    redemptionRoad: {
      title: "Redemption Road",
      authorKeys: [Person.JOHN_HART],
      meeting: "2016.11.28",
      dcl: "1316552114",
    },
    sharpObjects: {
      title: "Sharp Objects",
      authorKeys: [Person.GILLIAN_FLYNN],
      dcl: "767353114",
      lt: "work/1117152",
    },
    sheWhoWasNoMore: {
      title: "She Who Was No More",
      authorKeys: [Person.BOILEAU_NARCEJAC],
      series: [SeriesEntry.create(Series.PETER_SWANSON_SUGGESTS, 2)],
      gr: "book/show/25241971",
    },
    sixYears: {
      title: "Six Years",
      authorKeys: [Person.HARLAN_COBEN],
      meeting: "2013.09.23",
      dcl: "1134102114",
    },
    stayClose: {
      title: "Stay Close",
      authorKeys: [Person.HARLAN_COBEN],
      meeting: "2013.01.28",
      dcl: "1022395114",
    },
    stillLife: {
      title: "Still Life",
      authorKeys: [Person.LOUISE_PENNY],
      series: [
        SeriesEntry.create(Series.CHIEF_INSPECTOR_ARMAND_GAMACHE, 1),
        SeriesEntry.create(Series.GAIL_H_SUGGESTS, 1),
      ],
      lt: "work/544362",
    },
    stoneCold2007: {
      title: "Stone Cold (2007)",
      authorKeys: [Person.DAVID_BALDACCI],
      series: [SeriesEntry.create(Series.THE_CAMEL_CLUB, 3)],
      lt: "work/3592880",
      wiki: "Stone_Cold_(Baldacci_novel)",
    },
    stoneCold2014: {
      title: "Stone Cold (2014)",
      authorKeys: [Person.CJ_BOX],
      series: [SeriesEntry.create(Series.JOE_PICKETT, 14)],
      meeting: "2015.09.28",
      dcl: "1180990114",
    },
    strangersOnATrain: {
      title: "Strangers on a Train",
      authorKeys: [Person.PATRICIA_HIGHSMITH],
      series: [SeriesEntry.create(Series.PERFECT_MURDERS_LIST, 5)],
      lt: "work/126353",
    },
    suspect: {
      title: "Suspect",
      authorKeys: [Person.ROBERT_CRAIS],
      meeting: "2014.01.27",
      dcl: "1087642114",
    },
    sweetheart: {
      title: "Sweetheart",
      authorKeys: [Person.CHELSEA_CAIN],
      series: [SeriesEntry.create(Series.GRETCHEN_LOWELL, 2)],
      lt: "work/8386014",
    },
    sweetLittleLies: {
      title: "Sweet Little Lies",
      authorKeys: [Person.CAZ_FREAR],
      series: [SeriesEntry.create(Series.CAT_KINSELLA, 1)],
      dcl: "1466868114",
      lt: "work/19582483",
      meeting: "2019.11.18",
    },
    sycamoreRow: {
      title: "Sycamore Row",
      authorKeys: [Person.JOHN_GRISHAM],
      series: [SeriesEntry.create(Series.JAKE_BRIGANCE, 2)],
      meeting: "2014.11.24",
      dcl: "1151120114",
      lt: "work/13638462",
    },
    thatNight: {
      title: "That Night",
      authorKeys: [Person.CHEVY_STEVENS],
      meeting: "2015.06.22",
      dcl: "1189725114",
    },
    theAbcMurders: {
      title: "The A.B.C. Murders",
      authorKeys: [Person.AGATHA_CHRISTIE],
      series: [
        SeriesEntry.create(Series.HERCULE_POIROT, 12),
        SeriesEntry.create(Series.PERFECT_MURDERS_LIST, 3),
      ],
      lt: "work/30637",
    },
    theAx: {
      title: "The Ax",
      authorKeys: [Person.DONALD_E_WESTLAKE],
      series: [SeriesEntry.create(Series.PETER_SWANSON_SUGGESTS, 3)],
      gr: "book/show/176811.The_Ax",
      lt: "work/177297",
    },
    theBlackEcho: {
      title: "The Black Echo",
      authorKeys: [Person.MICHAEL_CONNELLY],
      series: [SeriesEntry.create(Series.HARRY_BOSCH, 1)],
      dcl: "871416114",
      lt: "work/84315",
    },
    theBlackWidow: {
      title: "The Black Widow",
      authorKeys: [Person.DANIEL_SILVA],
      series: [SeriesEntry.create(Series.GABRIEL_ALLON, 16)],
      meeting: "2017.06.26",
      dcl: "1317748114",
    },
    theBoneParade: {
      title: "The Bone Parade",
      authorKeys: [Person.MARK_NYKANEN],
      meeting: "2007.05.21",
      lt: "work/359059",
    },
    theBrassVerdict: {
      title: "The Brass Verdict",
      authorKeys: [Person.MICHAEL_CONNELLY],
      series: [
        SeriesEntry.create(Series.MICKEY_HALLER, 2),
        SeriesEntry.create(Series.HARRY_BOSCH, 14),
      ],
      meeting: "2012.03.26",
      dcl: "875367114",
    },
    theBrideCollector: {
      title: "The Bride Collector",
      authorKeys: [Person.TED_DEKKER],
      meeting: "2010.08.23",
      dcl: "972555114",
    },
    theBrokenWindow: {
      title: "The Broken Window",
      authorKeys: [Person.JEFFERY_DEAVER],
      series: [SeriesEntry.create(Series.LINCOLN_RHYME, 8)],
      meeting: "2009.08.24",
      dcl: "856637114",
    },
    theBrutalTelling: {
      title: "The Brutal Telling",
      authorKeys: [Person.LOUISE_PENNY],
      series: [SeriesEntry.create(Series.CHIEF_INSPECTOR_ARMAND_GAMACHE, 5)],
      meeting: "2010.06.28",
      dcl: "932000114",
      lt: "work/8410558",
    },
    theCamelClub: {
      title: "The Camel Club",
      authorKeys: [Person.DAVID_BALDACCI],
      series: [SeriesEntry.create(Series.THE_CAMEL_CLUB, 1)],
      lt: "work/977305",
      wiki: "The_Camel_Club_(novel)",
    },
    theChristmasCrimesAtPuzzelManor: {
      title: "The Christmas Crimes at Puzzel Manor",
      authorKeys: [Person.SIMON_BRETT],
      meeting: "2018.12.14",
      lt: "work/96153",
    },
    theCollectors: {
      title: "The Collectors",
      authorKeys: [Person.DAVID_BALDACCI],
      series: [SeriesEntry.create(Series.THE_CAMEL_CLUB, 2)],
      lt: "work/990503",
      wiki: "The_Collectors_(novel)",
    },
    theCoupleNextDoor: {
      title: "The Couple Next Door",
      authorKeys: [Person.SHARI_LAPENA],
      meeting: "2018.03.26",
      dcl: "1348740114",
    },
    theCrossing: {
      title: "The Crossing",
      authorKeys: [Person.MICHAEL_CONNELLY],
      series: [SeriesEntry.create(Series.HARRY_BOSCH, 18)],
      meeting: "2016.09.26",
      dcl: "1277014114",
    },
    theDeathOfMrsWestaway: {
      title: "The Death of Mrs. Westaway",
      authorKeys: [Person.RUTH_WARE],
      dcl: "1446736114",
      lt: "work/20792311",
      meeting: "2019.08.26",
    },
    theDepartmentOfSensitiveCrimes: {
      title: "The Department of Sensitive Crimes",
      authorKeys: [Person.ALEXANDER_MCCALL_SMITH],
      series: [SeriesEntry.create(Series.DETECTIVE_VARG, 1)],
      dcl: "1535041114",
      lt: "work/22451389",
      meeting: "2020.07.27",
    },
    theDrowner: {
      title: "The Drowner",
      authorKeys: [Person.JOHN_D_MACDONALD],
      series: [SeriesEntry.create(Series.PERFECT_MURDERS_LIST, 6)],
      lt: "work/842541",
    },
    theDry: {
      title: "The Dry",
      authorKeys: [Person.JANE_HARPER],
      series: [SeriesEntry.create(Series.AARON_FALK, 1)],
      dcl: "1364617114",
      lt: "work/17442790",
      meeting: "2019.03.25",
    },
    theEnglishSpy: {
      title: "The English Spy",
      authorKeys: [Person.DANIEL_SILVA],
      series: [SeriesEntry.create(Series.GABRIEL_ALLON, 15)],
      meeting: "2017.04.24",
      dcl: "1466247114",
    },
    theEscapeRoom: {
      title: "The Escape Room",
      authorKeys: [Person.MEGAN_GOLDIN],
      dcl: "1565306114",
      lt: "work/22043625",
      meeting: "2020.02.24",
    },
    theExpats: {
      title: "The Expats",
      authorKeys: [Person.CHRIS_PAVONE],
      meeting: "2014.02.24",
      dcl: "1028931114",
    },
    theFallen: {
      title: "The Fallen",
      authorKeys: [Person.DAVID_BALDACCI],
      series: [SeriesEntry.create(Series.AMOS_DECKER, 4)],
      dcl: "1441565114",
      lt: "work/20582252",
      meeting: "2019.01.28",
    },
    theFamilyUpstairs: {
      title: "The Family Upstairs",
      authorKeys: [Person.LISA_JEWELL],
      dcl: "1595383114",
      lt: "work/23187308",
      meeting: "2020.08.24",
    },
    theFifthWitness: {
      title: "The Fifth Witness",
      authorKeys: [Person.MICHAEL_CONNELLY],
      series: [SeriesEntry.create(Series.MICKEY_HALLER, 4)],
      meeting: "2013.04.22",
      dcl: "985297114",
    },
    theFinalSolution: {
      title: "The Final Solution",
      authorKeys: [Person.MICHAEL_CHABON],
      meeting: "2007.03.26",
      lt: "work/8108",
    },
    theGirlWhoKickedTheHornetsNest: {
      title: "The Girl Who Kicked the Hornet's Nest",
      authorKeys: [Person.STIEG_LARSSON],
      series: [SeriesEntry.create(Series.MILLENNIUM, 3)],
      meeting: "2011.07.25",
      dcl: "946979114",
    },
    theGirlWhoPlayedWithFire: {
      title: "The Girl Who Played with Fire",
      authorKeys: [Person.STIEG_LARSSON],
      series: [SeriesEntry.create(Series.MILLENNIUM, 2)],
      meeting: "2010.10.25",
      dcl: "1210737114",
    },
    theGirlWithTheDragonTattoo: {
      title: "The Girl with the Dragon Tattoo",
      authorKeys: [Person.STIEG_LARSSON],
      series: [SeriesEntry.create(Series.MILLENNIUM, 1)],
      meeting: "2009.07.27",
      dcl: "1087244114",
    },
    theGodsOfGuilt: {
      title: "The Gods Of Guilt",
      authorKeys: [Person.MICHAEL_CONNELLY],
      series: [SeriesEntry.create(Series.MICKEY_HALLER, 5)],
      meeting: "2015.02.23",
      dcl: "1154561114",
    },
    theGreekCoffinMystery: {
      title: "The Greek Coffin Mystery",
      authorKeys: [Person.ELLERY_QUEEN],
      series: [SeriesEntry.create(Series.ELLERY_QUEEN, 4)],
      meeting: "2015.11.23",
      dcl: "1294792114",
    },
    theGuilty: {
      title: "The Guilty",
      authorKeys: [Person.DAVID_BALDACCI],
      series: [SeriesEntry.create(Series.WILL_ROBIE, 4)],
      meeting: "2016.08.22",
      dcl: "1277015114",
      lt: "work/15802151",
    },
    theHeist: {
      title: "The Heist",
      authorKeys: [Person.DANIEL_SILVA],
      series: [SeriesEntry.create(Series.GABRIEL_ALLON, 14)],
      meeting: "2015.10.26",
      dcl: "1211991114",
    },
    theHoundOfTheBaskervilles: {
      title: "The Hound of the Baskervilles",
      authorKeys: [Person.ARTHUR_CONAN_DOYLE],
      series: [SeriesEntry.create(Series.SHERLOCK_HOLMES, 5)],
      meeting: "2007.10.22",
      dcl: "1007856114",
    },
    theHuntClub: {
      title: "The Hunt Club",
      authorKeys: [Person.JOHN_LESCROART],
      meeting: "2007.09.24",
      lt: "work/554580",
    },
    theHush: {
      title: "The Hush",
      authorKeys: [Person.JOHN_HART],
      series: [SeriesEntry.create(Series.JOHNNY_MERRIMON, 2)],
      meeting: "2018.10.22",
      dcl: "1431235114",
    },
    theInnocentMan: {
      title: "The Innocent Man",
      authorKeys: [Person.JOHN_GRISHAM],
      meeting: "2008.01.28",
      dcl: "767190114",
    },
    theKeepsake: {
      title: "The Keepsake",
      authorKeys: [Person.TESS_GERRITSEN],
      meeting: "2009.11.23",
      dcl: "1018803114",
    },
    theKillerNextDoor: {
      title: "The Killer Next Door",
      authorKeys: [Person.ALEX_MARWOOD],
      meeting: "2016.03.28",
      dcl: "1233151114",
    },
    theKillingsAtBadgersDrift: {
      title: "The Killings at Badger's Drift",
      authorKeys: [Person.CAROLINE_GRAHAM],
      series: [SeriesEntry.create(Series.CHIEF_INSPECTOR_BARNABY_MYSTERIES, 1)],
      lt: "work/270034",
    },
    theLastChild: {
      title: "The Last Child",
      authorKeys: [Person.JOHN_HART],
      series: [SeriesEntry.create(Series.JOHNNY_MERRIMON, 1)],
      meeting: "2012.07.23",
      dcl: "1021303114",
    },
    theLastPaintingOfSaraDeVos: {
      title: "The Last Painting of Sara de Vos",
      authorKeys: [Person.DOMINIC_SMITH],
      meeting: "2017.01.23",
      dcl: "1305320114",
    },
    theLateShow: {
      title: "The Late Show",
      authorKeys: [Person.MICHAEL_CONNELLY],
      series: [SeriesEntry.create(Series.RENEE_BALLARD, 1)],
      meeting: "2018.04.23",
      dcl: "1402219114",
    },
    theLeopard: {
      title: "The Leopard",
      authorKeys: [Person.JO_NESBO],
      series: [SeriesEntry.create(Series.HARRY_HOLE, 8)],
      meeting: "2013.03.25",
      dcl: "1020521114",
    },
    theLincolnLawyer: {
      title: "The Lincoln Lawyer",
      authorKeys: [Person.MICHAEL_CONNELLY],
      series: [SeriesEntry.create(Series.MICKEY_HALLER, 1)],
      meeting: "2011.09.26",
      dcl: "985297114",
      lt: "work/25501",
    },
    theLostMan: {
      title: "The Lost Man",
      authorKeys: [Person.JANE_HARPER],
      dcl: "1523223114",
      lt: "work/21919798",
      meeting: "2020.05.20",
    },
    theMostDangerousThing: {
      title: "The Most Dangerous Thing",
      authorKeys: [Person.LAURA_LIPPMAN],
      meeting: "2012.08.27",
      dcl: "1004847114",
    },
    theMysteriousAffairAtStyles: {
      title: "The Mysterious Affair at Styles",
      authorKeys: [Person.AGATHA_CHRISTIE],
      series: [SeriesEntry.create(Series.HERCULE_POIROT, 1)],
      meeting: "2013.12.16",
      dcl: "783597114",
      lt: "work/2921950",
    },
    theNarrows: {
      title: "The Narrows",
      authorKeys: [Person.MICHAEL_CONNELLY],
      series: [SeriesEntry.create(Series.HARRY_BOSCH, 10)],
      meeting: "2009.05.18",
      dcl: "648301114",
    },
    theNightSeason: {
      title: "The Night Season",
      authorKeys: [Person.CHELSEA_CAIN],
      series: [SeriesEntry.create(Series.GRETCHEN_LOWELL, 4)],
      meeting: "2012.10.22",
      lt: "work/10349831",
    },
    theNowhereMan: {
      title: "The Nowhere Man",
      authorKeys: [Person.GREGG_HURWITZ],
      series: [SeriesEntry.create(Series.EVAN_SMOAK, 2)],
      meeting: "2017.11.27",
      dcl: "1364629114",
    },
    thePallbearers: {
      title: "The Pallbearers",
      authorKeys: [Person.STEPHEN_J_CANNELL],
      series: [SeriesEntry.create(Series.SHANE_SCULLY, 9)],
      meeting: "2011.01.24",
      dcl: "946057114",
    },
    theProgram: {
      title: "The Program",
      authorKeys: [Person.STEPHEN_WHITE],
      series: [SeriesEntry.create(Series.DR_ALAN_GREGORY, 9)],
      meeting: "2008.06.23",
      dcl: "1382906114",
    },
    thePromise: {
      title: "The Promise",
      authorKeys: [Person.ROBERT_CRAIS],
      series: [
        SeriesEntry.create(Series.ELVIS_COLE, 14),
        SeriesEntry.create(Series.JOE_PIKE, 5),
      ],
      meeting: "2016.07.25",
      dcl: "1224417114",
    },
    theRedHouseMystery: {
      title: "The Red House Mystery",
      authorKeys: [Person.AA_MILNE],
      series: [SeriesEntry.create(Series.PERFECT_MURDERS_LIST, 1)],
      lt: "work/247700",
    },
    theRembrandtAffair: {
      title: "The Rembrandt Affair",
      authorKeys: [Person.DANIEL_SILVA],
      series: [SeriesEntry.create(Series.GABRIEL_ALLON, 10)],
      meeting: "2013.02.25",
      dcl: "956553114",
    },
    theReversal: {
      title: "The Reversal",
      authorKeys: [Person.MICHAEL_CONNELLY],
      series: [SeriesEntry.create(Series.MICKEY_HALLER, 3)],
      meeting: "2012.12.17",
      dcl: "967577114",
    },
    theSantaKlausMurder: {
      title: "The Santa Klaus Murder",
      authorKeys: [Person.MAVIS_DORIEL_HAY],
      lt: "work/14422101",
      meeting: "2019.12.13",
    },
    theSecretHistory: {
      title: "The Secret History",
      authorKeys: [Person.DONNA_TARTT],
      series: [SeriesEntry.create(Series.PERFECT_MURDERS_LIST, 8)],
      lt: "work/7221",
    },
    theShadowTracer: {
      title: "The Shadow Tracer",
      authorKeys: [Person.MEG_GARDINER],
      meeting: "2014.05.19",
      dcl: "1129797114",
    },
    theSilentPatient: {
      title: "The Silent Patient",
      authorKeys: [Person.ALEX_MICHAELIDES],
      dcl: "1531671114",
      lt: "work/21942360",
      meeting: "2020.03.23",
    },
    theSnowman: {
      title: "The Snowman",
      authorKeys: [Person.JO_NESBO],
      series: [SeriesEntry.create(Series.HARRY_HOLE, 7)],
      meeting: "2012.06.25",
      dcl: "990752114",
    },
    theStranger: {
      title: "The Stranger",
      authorKeys: [Person.HARLAN_COBEN],
      meeting: "2016.04.25",
      dcl: "1245665114",
    },
    theStupidestAngel: {
      title: "The Stupidest Angel",
      authorKeys: [Person.CHRISTOPHER_MOORE],
      meeting: "2007.12.17",
      dcl: "1257000114",
    },
    theSweetnessAtTheBottomOfThePie: {
      title: "The Sweetness at the Bottom of the Pie",
      authorKeys: [Person.ALAN_BRADLEY],
      series: [SeriesEntry.create(Series.FLAVIA_DE_LUCE, 1)],
      meeting: "2010.01.25",
      dcl: "906895114",
    },
    theThinMan: {
      title: "The Thin Man",
      authorKeys: [Person.DASHIELL_HAMMETT],
      meeting: "2009.02.23",
      dcl: "811460114",
    },
    theTravelers: {
      title: "The Travelers",
      authorKeys: [Person.CHRIS_PAVONE],
      meeting: "2016.10.24",
      dcl: "1300055114",
    },
    theTurnOfTheKey: {
      title: "The Turn of the Key",
      authorKeys: [Person.RUTH_WARE],
      dcl: "1576431114",
      lt: "work/22533612",
      meeting: "2020.11.16",
    },
    theTwoMinuteRule: {
      title: "The Two Minute Rule",
      authorKeys: [Person.ROBERT_CRAIS],
      meeting: "2008.04.28",
      dcl: "1260719114",
    },
    theWatchman: {
      title: "The Watchman",
      authorKeys: [Person.ROBERT_CRAIS],
      series: [SeriesEntry.create(Series.JOE_PIKE, 1)],
      meeting: "2012.09.24",
      dcl: "787076114",
    },
    theWitchElm: {
      title: "The Witch Elm",
      authorKeys: [Person.TANA_FRENCH],
      dcl: "1483240114",
      lt: "work/21676484",
      meeting: "2019.05.20",
    },
    theWomanInCabin10: {
      title: "The Woman in Cabin 10",
      authorKeys: [Person.RUTH_WARE],
      meeting: "2017.07.24",
      dcl: "1317758114",
    },
    theWomanInTheWindow: {
      title: "The Woman in the Window",
      authorKeys: [Person.AJ_FINN],
      meeting: "2018.11.26",
      dcl: "1430700114",
    },
    theWoods: {
      title: "The Woods",
      authorKeys: [Person.HARLAN_COBEN],
      meeting: "2008.09.22",
      dcl: "1615407114",
    },
    theWordIsMurder: {
      title: "The Word is Murder",
      authorKeys: [Person.ANTHONY_HOROWITZ],
      dcl: "1456731114",
      lt: "work/19570511",
      meeting: "2020.04.27",
    },
    theWrongSideOfGoodbye: {
      title: "The Wrong Side of Goodbye",
      authorKeys: [Person.MICHAEL_CONNELLY],
      series: [SeriesEntry.create(Series.HARRY_BOSCH, 19)],
      meeting: "2017.09.25",
      dcl: "1337567114",
    },
    trailOfBlood: {
      title: "Trail of Blood",
      authorKeys: [Person.LISA_BLACK],
      meeting: "2011.05.23",
      dcl: "968608114",
      lt: "work/10216273",
    },
    tripTych: {
      title: "TripTych",
      authorKeys: [Person.KARIN_SLAUGHTER],
      meeting: "2009.01.26",
      dcl: "755715114",
    },
    trueEvil: {
      title: "True Evil",
      authorKeys: [Person.GREG_ILES],
      meeting: "2009.04.27",
      dcl: "1075138114",
    },
    twoKindsOfTruth: {
      title: "Two Kinds of Truth",
      authorKeys: [Person.MICHAEL_CONNELLY],
      series: [SeriesEntry.create(Series.HARRY_BOSCH, 22)],
      meeting: "2018.08.27",
      dcl: "1412693114",
    },
    underMySkin: {
      title: "Under My Skin",
      authorKeys: [Person.LISA_UNGER],
      dcl: "1483237114",
      lt: "work/21404705",
      meeting: "2019.04.22",
    },
    vanishingGames: {
      title: "Vanishing Games",
      authorKeys: [Person.ROGER_HOBBS],
      series: [SeriesEntry.create(Series.GHOSTMAN, 2)],
      meeting: "2016.05.23",
      dcl: "1283492114",
    },
    vertigo: {
      title: "Vertigo",
      authorKeys: [Person.BOILEAU_NARCEJAC],
      series: [SeriesEntry.create(Series.PETER_SWANSON_SUGGESTS, 1)],
      gr: "book/show/141328.Vertigo",
      lt: "work/397208",
    },
    victims: {
      title: "Victims",
      authorKeys: [Person.JONATHAN_KELLERMAN],
      series: [SeriesEntry.create(Series.ALEX_DELAWARE, 27)],
      meeting: "2013.07.22",
      dcl: "1030014114",
    },
    waitingForWednesday: {
      title: "Waiting for Wednesday",
      authorKeys: [Person.NICCI_FRENCH],
      series: [SeriesEntry.create(Series.FRIEDA_KLEIN, 3)],
      meeting: "2014.09.22",
      dcl: "1185773114",
    },
    whatTheDeadKnow: {
      title: "What the Dead Know",
      authorKeys: [Person.LAURA_LIPPMAN],
      meeting: "2008.07.28",
      dcl: "801592114",
    },
    whenTheWindBlows: {
      title: "When the Wind Blows",
      authorKeys: [Person.JAMES_PATTERSON],
      meeting: "2007.10.22",
      dcl: "1243797114",
    },
    whereTheCrawdadsSing: {
      title: "Where the Crawdads Sing",
      authorKeys: [Person.DELIA_OWENS],
      dcl: "1485412114",
      lt: "work/21599568",
      meeting: "2019.09.23",
    },
    whispersOfTheDead: {
      title: "Whispers of the Dead",
      authorKeys: [Person.SIMON_BECKETT],
      series: [SeriesEntry.create(Series.DAVID_HUNTER, 3)],
      meeting: "2010.03.22",
      lt: "work/7598433",
    },
    wickedPrey: {
      title: "Wicked Prey",
      authorKeys: [Person.JOHN_SANDFORD],
      series: [SeriesEntry.create(Series.LUCAS_DAVENPORT, 19)],
      meeting: "2009.12.28",
      dcl: "902064114",
    },
    you: {
      title: "You",
      authorKeys: [Person.CAROLINE_KEPNES],
      series: [
        SeriesEntry.create(Series.YOU, 1),
        SeriesEntry.create(Series.PETER_SWANSON_SUGGESTS, 4),
      ],
      dcl: "1228707114",
      gr: "book/show/36430011-you",
      lt: "work/14851657",
    },
  },
};

Book.keys = () => Object.keys(Book.properties);

Book.values = () => Object.values(Book.properties);

// /////////////////////////////////////////////////////////////////////////////
const seriesKeys = (book) =>
  book && book.series ? R.map(R.prop("key"), book.series) : [];

Book.authorKeyToBooks = (isMeeting = false) => {
  const books = isMeeting ? Book.valuesWithMeeting() : Book.values();
  const putBook = (accum, authorKey, book) => {
    const oldBooks = accum[authorKey] || [];
    const newBooks = R.append(book, oldBooks);

    return R.assoc(authorKey, newBooks, accum);
  };
  const reduceFunction = (accum, book) => {
    const { authorKeys } = book;
    const reduceFunction2 = (accum2, key) => putBook(accum2, key, book);

    return R.reduce(reduceFunction2, accum, authorKeys);
  };

  return R.reduce(reduceFunction, {}, books);
};

Book.seriesKeyToBooks = (isMeeting = false) => {
  const books = isMeeting ? Book.valuesWithMeeting() : Book.values();
  const putBook = (accum, series, book) => {
    const oldBooks = accum[series.key] || [];
    const newBooks = R.append(book, oldBooks);

    return R.assoc(series.key, newBooks, accum);
  };
  const reduceFunction = (accum, book) => {
    const { series } = book;
    let answer = accum;

    if (series) {
      const reduceFunction2 = (accum2, key) => putBook(accum2, key, book);
      answer = R.reduce(reduceFunction2, accum, series);
    }

    return answer;
  };

  return R.reduce(reduceFunction, {}, books);
};

Book.valuesBySeries = (seriesKey) => {
  let answer = [];

  if (seriesKey) {
    const books = Object.values(Book.properties);
    const filterFunction = (book) => seriesKeys(book).includes(seriesKey);
    answer = R.filter(filterFunction, books);
  }

  return answer;
};

Book.valuesByYear = (year) => {
  const books = Object.values(Book.properties);
  const filterFunction = (book) => {
    const year0 = book.meeting ? parseInt(book.meeting.substring(0, 4), 10) : 0;

    return year0 === year;
  };

  return R.filter(filterFunction, books);
};

Book.valuesWithMeeting = () => {
  const books = Object.values(Book.properties);
  const filterFunction = (book) => !R.isNil(book.meeting);

  return R.filter(filterFunction, books);
};

Book.valuesWithoutMeeting = () => {
  const books = Object.values(Book.properties);
  const filterFunction = (book) => R.isNil(book.meeting);

  return R.filter(filterFunction, books);
};

Object.freeze(Book);

module.exports = Book;
