const WIKI_PREFIX = "https://en.wikipedia.org/wiki/";

const Person = {
  AJ_FINN: "ajFinn",
  ALEX_MARWOOD: "alexMarwood",
  ALEX_MICHAELIDES: "alexMichaelides",
  ALEXANDER_MCCALL_SMITH: "alexanderMcCallSmith",
  AMY_ADAMS: "amyAdams",
  ANTHONY_HOROWITZ: "anthonyHorowitz",
  BA_PARIS: "baParis",
  BEN_AFFLECK: "benAffleck",
  BRIDGET_FONDA: "bridgetFonda",
  CAZ_FREAR: "cazFrear",
  CHB_KITCHIN: "chbKitchin",
  CHELSEA_CAIN: "chelseaCain",
  CHEVY_STEVENS: "chevyStevens",
  CHRIS_PAVONE: "chrisPavone",
  CJ_BOX: "cjBox",
  CLARE_MACKINTOSH: "clareMackintosh",
  COBIE_SMULDERS: "cobieSmulders",
  DANIEL_SILVA: "danielSilva",
  DAVID_BALDACCI: "davidBaldacci",
  DELIA_OWENS: "deliaOwens",
  DOMINIC_SMITH: "dominicSmith",
  ELLERY_QUEEN: "elleryQueen",
  EMELIE_SCHEPP: "emelieSchepp",
  ERIC_BANA: "ericBana",
  GABRIEL_BYRNE: "gabrielByrne",
  GENEVIEVE_OREILLY: "genevieveOReilly",
  GEORGETTE_HEYER: "georgetteHeyer",
  GILLIAN_FLYNN: "gillianFlynn",
  GREGG_HURWITZ: "greggHurwitz",
  HARLAN_COBEN: "harlanCoben",
  HARVEY_KEITEL: "harveyKeitel",
  JANE_HARPER: "janeHarper",
  JEFF_LINDSAY: "jeffLindsay",
  JENNIFER_CARPENTER: "jenniferCarpenter",
  JOHN_GRISHAM: "johnGrisham",
  JOHN_HART: "johnHart",
  JOHN_NETTLES: "johnNettles",
  JONATHAN_KELLERMAN: "jonathanKellerman",
  JO_NESBO: "joNesbo",
  KARIN_SLAUGHTER: "karinSlaughter",
  KIMBERLY_MCCREIGHT: "kimberlyMcCreight",
  LEE_CHILD: "leeChild",
  LENA_OLIN: "lenaOlin",
  LIANE_MORIARTY: "lianeMoriarty",
  LISA_JEWELL: "lisaJewell",
  LISA_UNGER: "lisaUnger",
  LUC_BESSON: "lucBesson",
  MARY_KUBICA: "maryKubica",
  MAVIS_DORIEL_HAY: "mavisDorielHay",
  MEGAN_GOLDIN: "meganGoldin",
  MICHAEL_C_HALL: "michaelCHall",
  MICHAEL_CONNELLY: "michaelConnelly",
  NEIL_DUDGEON: "neilDudgeon",
  NGAIO_MARSH: "ngaioMarsh",
  OWEN_LAUKKANEN: "owenLaukkanen",
  PATRICIA_CLARKSON: "patriciaClarkson",
  PETER_SWANSON: "peterSwanson",
  ROBERT_CRAIS: "robertCrais",
  ROBERT_GALBRAITH: "robertGalbraith",
  ROGER_HOBBS: "rogerHobbs",
  ROSAMUND_PIKE: "rosamundPike",
  RUTH_WARE: "ruthWare",
  SANDRA_BROWN: "sandraBrown",
  SHARI_LAPENA: "shariLapena",
  SIMON_BRETT: "simonBrett",
  TANA_FRENCH: "tanaFrench",
  TESS_GERRITSEN: "tessGerritsen",
  TOM_CRUISE: "tomCruise",

  properties: {
    ajFinn: { first: "A.J.", last: "Finn", wiki: "A._J._Finn" },
    alexMarwood: { first: "Alex", last: "Marwood", wiki: "Serena_Mackesy" },
    alexMichaelides: {
      first: "Alex",
      last: "Michaelides",
      wiki: "Alex_Michaelides",
    },
    alexanderMcCallSmith: {
      first: "Alexander",
      middle: "McCall",
      last: "Smith",
      wiki: "Alexander_McCall_Smith",
    },
    amyAdams: { first: "Amy", last: "Adams" },
    anthonyHorowitz: {
      first: "Anthony",
      last: "Horowitz",
      wiki: "Anthony_Horowitz",
    },
    baParis: { first: "B.A.", last: "Paris" },
    benAffleck: { first: "Ben", last: "Affleck", wiki: "Ben_Affleck" },
    bridgetFonda: { first: "Bridget", last: "Fonda", wiki: "Bridget_Fonda" },
    cazFrear: { first: "Caz", last: "Frear" },
    chbKitchin: { first: "C.H.B.", last: "Kitchin", wiki: "C._H._B._Kitchin" },
    chelseaCain: { first: "Chelsea", last: "Cain", wiki: "Chelsea_Cain" },
    chevyStevens: { first: "Chevy", last: "Stevens", wiki: "Chevy_Stevens" },
    chrisPavone: { first: "Chris", last: "Pavone", wiki: "Chris_Pavone" },
    cjBox: { first: "C.J.", last: "Box", wiki: "C._J._Box" },
    clareMackintosh: {
      first: "Clare",
      last: "Mackintosh",
      wiki: "Clare_Mackintosh",
    },
    cobieSmulders: { first: "Cobie", last: "Smulders" },
    danielSilva: {
      first: "Daniel",
      last: "Silva",
      wiki: "Daniel_Silva_(novelist)",
    },
    davidBaldacci: { first: "David", last: "Baldacci", wiki: "David_Baldacci" },
    deliaOwens: { first: "Delia", last: "Owens", wiki: "Delia_Owens" },
    dominicSmith: {
      first: "Dominic",
      last: "Smith",
      wiki: "Dominic_Smith_(author)",
    },
    elleryQueen: { first: "Ellery", last: "Queen", wiki: "Ellery_Queen" },
    emelieSchepp: { first: "Emelie", last: "Schepp", wiki: "Emelie_Schepp" },
    ericBana: { first: "Eric", last: "Bana", wiki: "Eric_Bana" },
    gabrielByrne: { first: "Gabriel", last: "Byrne", wiki: "Gabriel_Byrne" },
    genevieveOReilly: {
      first: "Genevieve",
      last: "O'Reilly",
      wiki: "Genevieve_O%27Reilly",
    },
    georgetteHeyer: {
      first: "Georgette",
      last: "Heyer",
      wiki: "Georgette_Heyer",
    },
    gillianFlynn: { first: "Gillian", last: "Flynn", wiki: "Gillian_Flynn" },
    greggHurwitz: { first: "Gregg", last: "Hurwitz", wiki: "Gregg_Hurwitz" },
    harlanCoben: { first: "Harlan", last: "Coben", wiki: "Harlan_Coben" },
    harveyKeitel: { first: "Harvey", last: "Keitel", wiki: "Harvey_Keitel" },
    janeHarper: { first: "Jane", last: "Harper", wiki: "Jane_Harper" },
    jeffLindsay: { first: "Jeff", last: "Lindsay" },
    jenniferCarpenter: { first: "Jennifer", last: "Carpenter" },
    johnGrisham: { first: "John", last: "Grisham", wiki: "John_Grisham" },
    johnHart: { first: "John", last: "Hart", wiki: "John_Hart_(author)" },
    johnNettles: { first: "John", last: "Nettles" },
    jonathanKellerman: {
      first: "Jonathan",
      last: "Kellerman",
      wiki: "Jonathan_Kellerman",
    },
    joNesbo: { first: "Jo", last: "Nesbø", wiki: "Jo_Nesbø" },
    karinSlaughter: {
      first: "Karin",
      last: "Slaughter",
      wiki: "Karin_Slaughter",
    },
    kimberlyMcCreight: {
      first: "Kimberly",
      last: "McCreight",
      wiki: "Kimberly_McCreight",
    },
    leeChild: { first: "Lee", last: "Child", wiki: "Lee_Child" },
    lenaOlin: { first: "Lena", last: "Olin", wiki: "Lena_Olin" },
    lianeMoriarty: { first: "Liane", last: "Moriarty", wiki: "Liane_Moriarty" },
    lisaJewell: { first: "Lisa", last: "Jewell", wiki: "Lisa_Jewell" },
    lisaUnger: { first: "Lisa", last: "Unger", wiki: "Lisa_Unger" },
    lucBesson: { first: "Luc", last: "Besson", wiki: "Luc_Besson" },
    maryKubica: { first: "Mary", last: "Kubica" },
    mavisDorielHay: {
      first: "Mavis",
      middle: "Doriel",
      last: "Hay",
      wiki: "Mavis_Doriel_Hay",
    },
    meganGoldin: { first: "Megan", last: "Goldin" },
    michaelCHall: { first: "Michael", middle: "C.", last: "Hall" },
    michaelConnelly: {
      first: "Michael",
      last: "Connelly",
      wiki: "Michael_Connelly",
    },
    neilDudgeon: { first: "Neil", last: "Dudgeon" },
    ngaioMarsh: { first: "Ngaio", last: "Marsh", wiki: "Ngaio_Marsh" },
    owenLaukkanen: { first: "Owen", last: "Laukkanen", wiki: "Owen_Laukkanen" },
    patriciaClarkson: { first: "Patricia", last: "Clarkson" },
    peterSwanson: { first: "Peter", last: "Swanson", wiki: "Peter_Swanson" },
    robertGalbraith: {
      first: "Robert",
      last: "Galbraith",
      wiki: "J._K._Rowling#Cormoran_Strike",
    },
    robertCrais: { first: "Robert", last: "Crais", wiki: "Robert_Crais" },
    rogerHobbs: { first: "Roger", last: "Hobbs", wiki: "Roger_Hobbs" },
    rosamundPike: { first: "Rosamund", last: "Pike", wiki: "Rosamund_Pike" },
    ruthWare: { first: "Ruth", last: "Ware", wiki: "Ruth_Ware" },
    sandraBrown: { first: "Sandra", last: "Brown", wiki: "Sandra_Brown" },
    shariLapena: { first: "Shari", last: "Lapena", wiki: "Shari_Lapena" },
    simonBrett: { first: "Simon", last: "Brett", wiki: "Simon_Brett" },
    tanaFrench: { first: "Tana", last: "French", wiki: "Tana_French" },
    tessGerritsen: { first: "Tess", last: "Gerritsen", wiki: "Tess_Gerritsen" },
    tomCruise: { first: "Tom", last: "Cruise", wiki: "Tom_Cruise" },
  },
};

Person.keys = () => Object.keys(Person.properties);

Person.values = () => Object.values(Person.properties);

// /////////////////////////////////////////////////////////////////////////////
Person.wikiUrl = (author) =>
  author.wiki ? `${WIKI_PREFIX}${author.wiki}` : null;

Object.freeze(Person);

module.exports = Person;
