const Person = {
  AGATHA_CHRISTIE: "agathaChristie",
  AJ_FINN: "ajFinn",
  ALAN_BRADLEY: "alanBradley",
  ALEX_MARWOOD: "alexMarwood",
  ALEX_MICHAELIDES: "alexMichaelides",
  ALEXANDER_MCCALL_SMITH: "alexanderMcCallSmith",
  ALICE_BLANCHARD: "aliceBlanchard",
  AMY_ADAMS: "amyAdams",
  ANTHONY_HOROWITZ: "anthonyHorowitz",
  ARTHUR_CONAN_DOYLE: "arthurConanDoyle",
  BA_PARIS: "baParis",
  BEN_AFFLECK: "benAffleck",
  BRIDGET_FONDA: "bridgetFonda",
  CAROLINE_GRAHAM: "carolineGraham",
  CAZ_FREAR: "cazFrear",
  CHARLES_TODD: "charlesTodd",
  CHB_KITCHIN: "chbKitchin",
  CHELSEA_CAIN: "chelseaCain",
  CHEVY_STEVENS: "chevyStevens",
  CHRIS_EVANS: "chrisEvans",
  CHRIS_PAVONE: "chrisPavone",
  CHRISTOPHER_MOORE: "christopherMoore",
  CJ_BOX: "cjBox",
  CLARE_MACKINTOSH: "clareMackintosh",
  COBIE_SMULDERS: "cobieSmulders",
  DANIEL_CRAIG: "danielCraig",
  DANIEL_SILVA: "danielSilva",
  DASHIELL_HAMMETT: "dashiellHammett",
  DAVID_BALDACCI: "davidBaldacci",
  DAVID_BURKE: "davidBurke",
  DAVID_ROSENFELT: "davidRosenfelt",
  DAVID_SUCHET: "davidSuchet",
  DEAN_KOONTZ: "deanKoontz",
  DELIA_OWENS: "deliaOwens",
  DENNIS_LEHANE: "dennisLehane",
  DOMINIC_SMITH: "dominicSmith",
  EDNA_BUCHANAN: "ednaBuchanan",
  EDWARD_HARDWICKE: "edwardHardwicke",
  ELLERY_QUEEN: "elleryQueen",
  EMELIE_SCHEPP: "emelieSchepp",
  ERIC_BANA: "ericBana",
  GABRIEL_BYRNE: "gabrielByrne",
  GENEVIEVE_OREILLY: "genevieveOReilly",
  GEORGETTE_HEYER: "georgetteHeyer",
  GILLIAN_ANDERSON: "gillianAnderson",
  GILLIAN_FLYNN: "gillianFlynn",
  GREGG_HURWITZ: "greggHurwitz",
  GREG_ILES: "gregIles",
  HARLAN_COBEN: "harlanCoben",
  HARVEY_KEITEL: "harveyKeitel",
  HUGH_FRASER: "hughFraser",
  JAMES_NORTON: "jamesNorton",
  JAMES_PATTERSON: "jamesPatterson",
  JAMIE_DORNAN: "jamieDornan",
  JAMIE_HECTOR: "jamieHector",
  JANE_HARPER: "janeHarper",
  JEFF_LINDSAY: "jeffLindsay",
  JEFFERY_DEAVER: "jefferyDeaver",
  JENNIFER_CARPENTER: "jenniferCarpenter",
  JEREMY_BRETT: "jeremyBrett",
  JESSE_KELLERMAN: "jesseKellerman",
  JOHN_GRISHAM: "johnGrisham",
  JOHN_HART: "johnHart",
  JOHN_LESCROART: "johnLescroart",
  JOHN_NETTLES: "johnNettles",
  JOHN_SANDFORD: "johnSandford",
  JONATHAN_KELLERMAN: "jonathanKellerman",
  JO_NESBO: "joNesbo",
  KARIN_SLAUGHTER: "karinSlaughter",
  KATE_ATKINSON: "kateAtkinson",
  KATHY_REICHS: "kathyReichs",
  KENNETH_BRANAGH: "kennethBranagh",
  KIMBERLY_MCCREIGHT: "kimberlyMcCreight",
  LAURA_LIPPMAN: "lauraLippman",
  LEE_CHILD: "leeChild",
  LENA_OLIN: "lenaOlin",
  LIANE_MORIARTY: "lianeMoriarty",
  LINWOOD_BARCLAY: "linwoodBarclay",
  LISA_BLACK: "lisaBlack",
  LISA_JACKSON: "lisaJackson",
  LISA_JEWELL: "lisaJewell",
  LISA_SCOTTOLINE: "lisaScottoline",
  LISA_UNGER: "lisaUnger",
  LOUISE_PENNY: "louisePenny",
  LUC_BESSON: "lucBesson",
  MARISA_TOMEI: "marisaTomei",
  MARK_NYKANEN: "markNykanen",
  MARY_KUBICA: "maryKubica",
  MATTHEW_MCCONAUGHEY: "matthewMcConaughey",
  MAVIS_DORIEL_HAY: "mavisDorielHay",
  MC_BEATON: "mcBeaton",
  MEGAN_GOLDIN: "meganGoldin",
  MEG_GARDINER: "megGardiner",
  MICHAEL_CHABON: "michaelChabon",
  MICHAEL_C_HALL: "michaelCHall",
  MICHAEL_CONNELLY: "michaelConnelly",
  MICHELE_SCOTT: "micheleScott",
  NEIL_DUDGEON: "neilDudgeon",
  NGAIO_MARSH: "ngaioMarsh",
  NICCI_FRENCH: "nicciFrench",
  OWEN_LAUKKANEN: "owenLaukkanen",
  PATRICIA_CLARKSON: "patriciaClarkson",
  PENELOPE_CRUZ: "penelopeCruz",
  PETER_SWANSON: "peterSwanson",
  RIAN_JOHNSON: "rianJohnson",
  ROBERT_CRAIS: "robertCrais",
  ROBERT_GALBRAITH: "robertGalbraith",
  ROBSON_GREEN: "robsonGreen",
  ROGER_HOBBS: "rogerHobbs",
  ROSAMUND_PIKE: "rosamundPike",
  RUTH_WARE: "ruthWare",
  SANDRA_BROWN: "sandraBrown",
  SARAH_LANCASHIRE: "sarahLancashire",
  SHARI_LAPENA: "shariLapena",
  SIMON_BECKETT: "simonBeckett",
  SIMON_BRETT: "simonBrett",
  STEPHEN_J_CANNELL: "stephenJCannell",
  STEPHEN_WHITE: "stephenWhite",
  STIEG_LARSSON: "stiegLarsson",
  STUART_WOODS: "stuartWoods",
  TANA_FRENCH: "tanaFrench",
  TED_DEKKER: "tedDekker",
  TESS_GERRITSEN: "tessGerritsen",
  TITUS_WELLIVER: "titusWelliver",
  TOM_CRUISE: "tomCruise",
  WILLIAM_LANDAY: "williamLanday",

  properties: {
    agathaChristie: {
      first: "Agatha",
      last: "Christie",
      imdb: "name/nm0002005",
      lt: "author/christieagatha",
      wiki: "Agatha_Christie",
    },
    ajFinn: { first: "A.J.", last: "Finn", wiki: "A._J._Finn" },
    alanBradley: {
      first: "Alan",
      last: "Bradley",
      wiki: "Alan_Bradley_(writer)",
    },
    alexMarwood: { first: "Alex", last: "Marwood", wiki: "Serena_Mackesy" },
    alexMichaelides: {
      first: "Alex",
      last: "Michaelides",
      imdb: "name/nm1955863",
      lt: "author/michaelidesalex",
      wiki: "Alex_Michaelides",
    },
    alexanderMcCallSmith: {
      first: "Alexander",
      middle: "McCall",
      last: "Smith",
      lt: "author/mccallsmithalexander",
      wiki: "Alexander_McCall_Smith",
    },
    aliceBlanchard: {
      first: "Alice",
      last: "Blanchard",
      lt: "author/blanchardalice",
      wiki: "Alice_Blanchard",
    },
    amyAdams: { first: "Amy", last: "Adams", imdb: "name/nm0010736" },
    anthonyHorowitz: {
      first: "Anthony",
      last: "Horowitz",
      imdb: "name/nm0395275",
      lt: "author/horowitzanthony",
      wiki: "Anthony_Horowitz",
    },
    arthurConanDoyle: {
      first: "Arthur",
      middle: "Conan",
      last: "Doyle",
      imdb: "name/nm0236279",
      lt: "author/doylearthurconan",
      wiki: "Arthur_Conan_Doyle",
    },
    baParis: { first: "B.A.", last: "Paris", lt: "author/parisba" },
    benAffleck: {
      first: "Ben",
      last: "Affleck",
      imdb: "name/nm0000255",
      wiki: "Ben_Affleck",
    },
    bridgetFonda: {
      first: "Bridget",
      last: "Fonda",
      imdb: "name/nm0000403",
      wiki: "Bridget_Fonda",
    },
    carolineGraham: {
      first: "Caroline",
      last: "Graham",
      imdb: "name/nm0333956",
      lt: "author/grahamcaroline-1",
      wiki: "Caroline_Graham",
    },
    cazFrear: { first: "Caz", last: "Frear", lt: "author/frearcaz" },
    charlesTodd: {
      first: "Charles",
      last: "Todd",
      wiki: "Caroline_and_Charles_Todd",
    },
    chbKitchin: {
      first: "C.H.B.",
      last: "Kitchin",
      lt: "author/kitchinchb",
      wiki: "C._H._B._Kitchin",
    },
    chelseaCain: {
      first: "Chelsea",
      last: "Cain",
      imdb: "name/nm4296249",
      lt: "author/cainchelsea",
      wiki: "Chelsea_Cain",
    },
    chevyStevens: { first: "Chevy", last: "Stevens", wiki: "Chevy_Stevens" },
    chrisEvans: {
      first: "Chris",
      last: "Evans",
      imdb: "name/nm0262635",
      wiki: "Chris_Evans_(actor)",
    },
    chrisPavone: {
      first: "Chris",
      last: "Pavone",
      imdb: "name/nm4949595",
      lt: "author/pavonechris",
      wiki: "Chris_Pavone",
    },
    christopherMoore: {
      first: "Christopher",
      last: "Moore",
      wiki: "Christopher_Moore_(author)",
    },
    cjBox: {
      first: "C.J.",
      last: "Box",
      imdb: "name/nm11353819",
      lt: "author/boxcj",
      wiki: "C._J._Box",
    },
    clareMackintosh: {
      first: "Clare",
      last: "Mackintosh",
      wiki: "Clare_Mackintosh",
    },
    cobieSmulders: {
      first: "Cobie",
      last: "Smulders",
      imdb: "name/nm1130627",
      wiki: "Cobie_Smulders",
    },
    danielCraig: {
      first: "Daniel",
      last: "Craig",
      imdb: "name/nm0185819",
      wiki: "Daniel_Craig",
    },
    danielSilva: {
      first: "Daniel",
      last: "Silva",
      lt: "author/silvadaniel",
      wiki: "Daniel_Silva_(novelist)",
    },
    dashiellHammett: {
      first: "Dashiell",
      last: "Hammett",
      lt: "author/hammettdashiell",
      wiki: "Dashiell_Hammett",
    },
    davidBaldacci: {
      first: "David",
      last: "Baldacci",
      imdb: "name/nm0049641",
      lt: "author/baldaccidavid",
      wiki: "David_Baldacci",
    },
    davidBurke: {
      first: "David",
      last: "Burke",
      imdb: "name/nm0121651",
      wiki: "David_Burke_(British_actor)",
    },
    davidRosenfelt: {
      first: "David",
      last: "Rosenfelt",
      wiki: "David_Rosenfelt",
    },
    davidSuchet: {
      first: "David",
      last: "Suchet",
      imdb: "name/nm0837064",
      wiki: "David_Suchet",
    },
    deanKoontz: { first: "Dean", last: "Koontz", wiki: "Dean_Koontz" },
    deliaOwens: {
      first: "Delia",
      last: "Owens",
      lt: "author/owensdelia",
      wiki: "Delia_Owens",
    },
    dennisLehane: { first: "Dennis", last: "Lehane", wiki: "Dennis_Lehane" },
    dominicSmith: {
      first: "Dominic",
      last: "Smith",
      wiki: "Dominic_Smith_(author)",
    },
    ednaBuchanan: { first: "Edna", last: "Buchanan", wiki: "Edna_Buchanan" },
    edwardHardwicke: {
      first: "Edward",
      last: "Hardwicke",
      imdb: "name/nm0362570",
      wiki: "Edward_Hardwicke",
    },
    elleryQueen: { first: "Ellery", last: "Queen", wiki: "Ellery_Queen" },
    emelieSchepp: { first: "Emelie", last: "Schepp", wiki: "Emelie_Schepp" },
    ericBana: {
      first: "Eric",
      last: "Bana",
      imdb: "name/nm0051509",
      wiki: "Eric_Bana",
    },
    gabrielByrne: {
      first: "Gabriel",
      last: "Byrne",
      imdb: "name/nm0000321",
      wiki: "Gabriel_Byrne",
    },
    genevieveOReilly: {
      first: "Genevieve",
      last: "O'Reilly",
      imdb: "name/nm0642444",
      wiki: "Genevieve_O%27Reilly",
    },
    georgetteHeyer: {
      first: "Georgette",
      last: "Heyer",
      wiki: "Georgette_Heyer",
    },
    gillianAnderson: {
      first: "Gillian",
      last: "Anderson",
      imdb: "name/nm0000096",
    },
    gillianFlynn: {
      first: "Gillian",
      last: "Flynn",
      imdb: "name/nm5058839",
      lt: "author/flynngillian",
      wiki: "Gillian_Flynn",
    },
    greggHurwitz: {
      first: "Gregg",
      last: "Hurwitz",
      lt: "author/hurwitzgregg",
      wiki: "Gregg_Hurwitz",
    },
    gregIles: {
      first: "Greg",
      last: "Iles",
      lt: "author/ilesgreg",
      wiki: "Greg_Iles",
    },
    harlanCoben: {
      first: "Harlan",
      last: "Coben",
      imdb: "name/nm1454192",
      lt: "author/cobenharlan",
      wiki: "Harlan_Coben",
    },
    harveyKeitel: {
      first: "Harvey",
      last: "Keitel",
      imdb: "name/nm0000172",
      wiki: "Harvey_Keitel",
    },
    hughFraser: {
      first: "Hugh",
      last: "Fraser",
      imdb: "name/nm0292140",
      wiki: "Hugh_Fraser_(actor)",
    },
    jamesNorton: { first: "James", last: "Norton", imdb: "name/nm3584268" },
    jamesPatterson: {
      first: "James",
      last: "Patterson",
      imdb: "name/nm0666248",
      lt: "author/pattersonjames-1",
      wiki: "James_Patterson",
    },
    jamieDornan: { first: "Jamie", last: "Dornan", imdb: "name/nm1946193" },
    jamieHector: {
      first: "Jamie",
      last: "Hector",
      imdb: "name/nm0373100",
      wiki: "Jamie_Hector",
    },
    janeHarper: {
      first: "Jane",
      last: "Harper",
      imdb: "name/nm7681091",
      lt: "author/harperjane-1",
      wiki: "Jane_Harper",
    },
    jeffLindsay: {
      first: "Jeff",
      last: "Lindsay",
      imdb: "name/nm2416255",
      lt: "author/lindsayjeff",
      wiki: "Jeff_Lindsay_(writer)",
    },
    jefferyDeaver: { first: "Jeffery", last: "Deaver", wiki: "Jeffery_Deaver" },
    jenniferCarpenter: {
      first: "Jennifer",
      last: "Carpenter",
      imdb: "name/nm1358539",
    },
    jeremyBrett: {
      first: "Jeremy",
      last: "Brett",
      imdb: "name/nm0107950",
      wiki: "Jeremy_Brett",
    },
    jesseKellerman: {
      first: "Jesse",
      last: "Kellerman",
      lt: "author/kellermanjesse",
    },
    johnGrisham: {
      first: "John",
      last: "Grisham",
      imdb: "name/nm0001300",
      lt: "author/grishamjohn",
      wiki: "John_Grisham",
    },
    johnHart: {
      first: "John",
      last: "Hart",
      lt: "author/hartjohn-1",
      wiki: "John_Hart_(author)",
    },
    johnLescroart: {
      first: "John",
      last: "Lescroart",
      lt: "author/lescroartjohn",
      wiki: "John_Lescroart",
    },
    johnNettles: { first: "John", last: "Nettles", imdb: "name/nm0626719" },
    johnSandford: {
      first: "John",
      last: "Sandford",
      imdb: "name/nm0761859",
      lt: "author/sandfordjohn-1",
      wiki: "John_Sandford_(novelist)",
    },
    jonathanKellerman: {
      first: "Jonathan",
      last: "Kellerman",
      imdb: "name/nm0445814",
      lt: "author/kellermanjonathan",
      wiki: "Jonathan_Kellerman",
    },
    joNesbo: {
      first: "Jo",
      last: "Nesbø",
      imdb: "name/nm1867674",
      lt: "author/nesbojo",
      wiki: "Jo_Nesbø",
    },
    karinSlaughter: {
      first: "Karin",
      last: "Slaughter",
      imdb: "name/nm4901740",
      lt: "author/slaughterkarin",
      wiki: "Karin_Slaughter",
    },
    kateAtkinson: { first: "Kate", last: "Atkinson", wiki: "Kate_Atkinson" },
    kathyReichs: { first: "Kathy", last: "Reichs", wiki: "Kathy_Reichs" },
    kennethBranagh: {
      first: "Kenneth",
      last: "Branagh",
      imdb: "name/nm0000110",
      wiki: "Kenneth_Branagh",
    },
    kimberlyMcCreight: {
      first: "Kimberly",
      last: "McCreight",
      wiki: "Kimberly_McCreight",
    },
    lauraLippman: {
      first: "Laura",
      last: "Lippman",
      imdb: "name/nm2887908",
      lt: "author/lippmanlaura-1",
      wiki: "Laura_Lippman",
    },
    leeChild: {
      first: "Lee",
      last: "Child",
      imdb: "name/nm1676193",
      lt: "author/childlee",
      wiki: "Lee_Child",
    },
    lenaOlin: {
      first: "Lena",
      last: "Olin",
      imdb: "name/nm0000565",
      wiki: "Lena_Olin",
    },
    lianeMoriarty: {
      first: "Liane",
      last: "Moriarty",
      lt: "author/moriartyliane",
      wiki: "Liane_Moriarty",
    },
    linwoodBarclay: {
      first: "Linwood",
      last: "Barclay",
      wiki: "Linwood_Barclay",
    },
    lisaBlack: { first: "Lisa", last: "Black", lt: "author/blacklisa-1" },
    lisaJackson: {
      first: "Lisa",
      last: "Jackson",
      wiki: "Lisa_Jackson_(author)",
    },
    lisaJewell: {
      first: "Lisa",
      last: "Jewell",
      lt: "author/jewelllisa",
      wiki: "Lisa_Jewell",
    },
    lisaScottoline: {
      first: "Lisa",
      last: "Scottoline",
      wiki: "Lisa_Scottoline",
    },
    lisaUnger: {
      first: "Lisa",
      last: "Unger",
      lt: "author/ungerlisa",
      wiki: "Lisa_Unger",
    },
    louisePenny: { first: "Louise", last: "Penny", wiki: "Louise_Penny" },
    lucBesson: { first: "Luc", last: "Besson", wiki: "Luc_Besson" },
    marisaTomei: {
      first: "Marisa",
      last: "Tomei",
      imdb: "name/nm0000673",
      wiki: "Marisa_Tomei",
    },
    markNykanen: {
      first: "Mark",
      last: "Nykanen",
      lt: "author/nykanenmark",
      wiki: "Mark_Nykanen",
    },
    maryKubica: { first: "Mary", last: "Kubica", lt: "author/kubicamary" },
    matthewMcConaughey: {
      first: "Matthew",
      last: "McConaughey",
      imdb: "name/nm0000190",
      wiki: "Matthew_McConaughey",
    },
    mavisDorielHay: {
      first: "Mavis",
      middle: "Doriel",
      last: "Hay",
      lt: "author/haymavisdoriel",
      wiki: "Mavis_Doriel_Hay",
    },
    mcBeaton: { first: "M.C.", last: "Beaton", wiki: "Marion_Chesney" },
    meganGoldin: { first: "Megan", last: "Goldin", lt: "author/goldinmegan" },
    megGardiner: {
      first: "Meg",
      last: "Gardiner",
      imdb: "name/nm3125172",
      lt: "author/gardinermeg",
      wiki: "Meg_Gardiner",
    },
    michaelChabon: {
      first: "Michael",
      last: "Chabon",
      lt: "author/chabonmichael",
      wiki: "Michael_Chabon",
    },
    michaelCHall: {
      first: "Michael",
      middle: "C.",
      last: "Hall",
      imdb: "name/nm0355910",
    },
    michaelConnelly: {
      first: "Michael",
      last: "Connelly",
      imdb: "name/nm0175093",
      lt: "author/connellymichael-1",
      wiki: "Michael_Connelly",
    },
    micheleScott: {
      first: "Michele",
      last: "Scott",
      lt: "author/scottmichele-1",
    },
    neilDudgeon: { first: "Neil", last: "Dudgeon", imdb: "name/nm0240072" },
    ngaioMarsh: { first: "Ngaio", last: "Marsh", wiki: "Ngaio_Marsh" },
    nicciFrench: {
      first: "Nicci",
      last: "French",
      lt: "author/frenchnicci",
      wiki: "Nicci_French",
    },
    owenLaukkanen: { first: "Owen", last: "Laukkanen", wiki: "Owen_Laukkanen" },
    patriciaClarkson: {
      first: "Patricia",
      last: "Clarkson",
      imdb: "name/nm0165101",
    },
    penelopeCruz: {
      first: "Penélope",
      last: "Cruz",
      imdb: "name/nm0004851",
      wiki: "Penélope_Cruz",
    },
    peterSwanson: {
      first: "Peter",
      last: "Swanson",
      lt: "author/swansonpeter-1",
      wiki: "Peter_Swanson",
    },
    rianJohnson: { first: "Rian", last: "Johnson", imdb: "name/nm0426059" },
    robertGalbraith: {
      first: "Robert",
      last: "Galbraith",
      lt: "author/galbraithrobert-1",
      wiki: "J._K._Rowling#Cormoran_Strike",
    },
    robertCrais: {
      first: "Robert",
      last: "Crais",
      imdb: "name/nm0186101",
      lt: "author/craisrobert",
      wiki: "Robert_Crais",
    },
    robsonGreen: { first: "Robson", last: "Green", imdb: "name/nm0338292" },
    rogerHobbs: {
      first: "Roger",
      last: "Hobbs",
      lt: "author/hobbsroger",
      wiki: "Roger_Hobbs",
    },
    rosamundPike: {
      first: "Rosamund",
      last: "Pike",
      imdb: "name/nm0683253",
      wiki: "Rosamund_Pike",
    },
    ruthWare: {
      first: "Ruth",
      last: "Ware",
      imdb: "name/nm3405121",
      lt: "author/wareruth",
      wiki: "Ruth_Ware",
    },
    sandraBrown: { first: "Sandra", last: "Brown", wiki: "Sandra_Brown" },
    sarahLancashire: {
      first: "Sarah",
      last: "Lancashire",
      imdb: "name/nm0484104",
    },
    shariLapena: { first: "Shari", last: "Lapena", wiki: "Shari_Lapena" },
    simonBeckett: {
      first: "Simon",
      last: "Beckett",
      lt: "author/beckettsimon",
      wiki: "Simon_Beckett",
    },
    simonBrett: {
      first: "Simon",
      last: "Brett",
      lt: "author/brettsimon-1",
      wiki: "Simon_Brett",
    },
    stephenJCannell: {
      first: "Stephen",
      middle: "J.",
      last: "Cannell",
      imdb: "name/nm0004798",
      wiki: "Stephen_J._Cannell",
    },
    stephenWhite: {
      first: "Stephen",
      last: "White",
      wiki: "Stephen_White_(author)",
    },
    stiegLarsson: {
      first: "Stieg",
      last: "Larsson",
      imdb: "name/nm2297183",
      lt: "author/larssonstieg",
      wiki: "Stieg_Larsson",
    },
    stuartWoods: { first: "Stuart", last: "Woods", wiki: "Stuart_Woods" },
    tanaFrench: {
      first: "Tana",
      last: "French",
      lt: "author/frenchtana",
      wiki: "Tana_French",
    },
    tedDekker: { first: "Ted", last: "Dekker", wiki: "Ted_Dekker" },
    tessGerritsen: {
      first: "Tess",
      last: "Gerritsen",
      imdb: "name/nm2446740",
      lt: "author/gerritsentess",
      wiki: "Tess_Gerritsen",
    },
    titusWelliver: {
      first: "Titus",
      last: "Welliver",
      imdb: "name/nm0920038",
      wiki: "Titus_Welliver",
    },
    tomCruise: {
      first: "Tom",
      last: "Cruise",
      imdb: "name/nm0000129",
      wiki: "Tom_Cruise",
    },
    williamLanday: { first: "William", last: "Landay", wiki: "William_Landay" },
  },
};

Person.keys = () => Object.keys(Person.properties);

Person.values = () => Object.values(Person.properties);

Object.freeze(Person);

module.exports = Person;
