const R = require("../node_modules/ramda/dist/ramda.js");

const Person = {
  AA_MILNE: "aaMilne",
  AGATHA_CHRISTIE: "Agatha Christie",
  AJ_FINN: "ajFinn",
  ALAN_BRADLEY: "alanBradley",
  ALEX_MARWOOD: "alexMarwood",
  ALEX_MICHAELIDES: "alexMichaelides",
  ALEX_PAVESI: "alexPavesi",
  ALEXANDER_MCCALL_SMITH: "alexanderMcCallSmith",
  ALEXANDRA_BENEDICT: "Alexandra Benedict",
  ALFRED_HITCHCOCK: "alfredHitchcock",
  ALICE_BLANCHARD: "aliceBlanchard",
  ALICE_FEENEY: "Alice Feeney",
  ALLAN_CUBITT: "allanCubitt",
  AL_PACINO: "alPacino",
  AMY_ADAMS: "amyAdams",
  AMY_TINTERA: "Amy Tintera",
  ANDREW_CHILD: "Andrew Child",
  ANNA_FRIEL: "annaFriel",
  ANTHONY_BERKELEY_COX: "anthonyBerkeleyCox",
  ANTHONY_HOROWITZ: "Anthony Horowitz",
  ARTHUR_CONAN_DOYLE: "arthurConanDoyle",
  BA_PARIS: "baParis",
  BARBARA_NICKLESS: "barbaraNickless",
  BARBARA_STANWYCK: "barbaraStanwyck",
  BARBARA_VINE: "barbaraVine",
  BEN_AFFLECK: "benAffleck",
  BENJAMIN_STEVENSON: "Benjamin Stevenson",
  BERTIE_CARVEL: "bertieCarvel",
  BILL_PAXTON: "billPaxton",
  BILLY_BOB_THORNTON: "billyBobThornton",
  BILLY_WILDER: "billyWilder",
  BOILEAU_NARCEJAC: "boileauNarcejac",
  BRIDGET_FONDA: "bridgetFonda",
  CAROLINE_GRAHAM: "carolineGraham",
  CAROLINE_KEPNES: "carolineKepnes",
  CAZ_FREAR: "cazFrear",
  CHARLES_BRANDT: "charlesBrandt",
  CHARLES_TODD: "charlesTodd",
  CHB_KITCHIN: "chbKitchin",
  CHELSEA_CAIN: "chelseaCain",
  CHEVY_STEVENS: "chevyStevens",
  CHRIS_CHIBNALL: "chrisChibnall",
  CHRIS_EVANS: "chrisEvans",
  CHRIS_PAVONE: "chrisPavone",
  CHRISTOPHER_MOORE: "christopherMoore",
  CHRISTOPHER_REEVE: "christopherReeve",
  CILLIAN_MURPHY: "cillianMurphy",
  CJ_BOX: "cjBox",
  CLARE_MACKINTOSH: "clareMackintosh",
  COBIE_SMULDERS: "cobieSmulders",
  CYRIL_COKE: "cyrilCoke",
  DANIEL_CRAIG: "danielCraig",
  DANIEL_SILVA: "danielSilva",
  DASHIELL_HAMMETT: "dashiellHammett",
  DAVID_BALDACCI: "davidBaldacci",
  DAVID_BURKE: "davidBurke",
  DAVID_ROSENFELT: "davidRosenfelt",
  DAVID_SUCHET: "davidSuchet",
  DAVID_TENNANT: "davidTennant",
  DAWN_FRENCH: "dawnFrench",
  DEAN_KOONTZ: "deanKoontz",
  DELIA_OWENS: "deliaOwens",
  DENNIS_LEHANE: "dennisLehane",
  DOMINIC_SMITH: "dominicSmith",
  DONALD_E_WESTLAKE: "donaldEWestlake",
  DONNA_TARTT: "donnaTartt",
  EDNA_BUCHANAN: "ednaBuchanan",
  EDWARD_G_ROBINSON: "edwardGRobinson",
  EDWARD_HARDWICKE: "edwardHardwicke",
  ELLERY_QUEEN: "elleryQueen",
  EMELIE_SCHEPP: "emelieSchepp",
  ERIC_BANA: "ericBana",
  ERIN_KELLY: "erinKelly",
  ETHEL_LINA_WHITE: "ethelLinaWhite",
  FABIAN_NICIEZA: "Fabian Nicieza",
  FARLEY_GRANGER: "farleyGranger",
  FRED_MACMURRAY: "fredMacmurray",
  GABRIEL_BYRNE: "gabrielByrne",
  GENEVIEVE_OREILLY: "genevieveOReilly",
  GEORGETTE_HEYER: "georgetteHeyer",
  GILLIAN_ANDERSON: "gillianAnderson",
  GILLIAN_FLYNN: "gillianFlynn",
  GK_CHESTERTON: "G.K. Chesterton",
  GREG_BERLANTI: "gregBerlanti",
  GREGG_HURWITZ: "greggHurwitz",
  GREG_ILES: "gregIles",
  HANS_ROSENFELDT: "hansRosenfeldt",
  HARLAN_COBEN: "Harlan Coben",
  HARVEY_KEITEL: "harveyKeitel",
  HUGH_DANCY: "hughDancy",
  HUGH_FRASER: "hughFraser",
  HYWEL_BENNETT: "hywelBennett",
  IAN_RANKIN: "ianRankin",
  IRA_LEVIN: "iraLevin",
  JAMES_M_CAIN: "jamesMCain",
  JAMES_NORTON: "jamesNorton",
  JAMES_OAKLEY: "jamesOakley",
  JAMES_PATTERSON: "jamesPatterson",
  JAMES_STEWART: "jamesStewart",
  JAMIE_DORNAN: "jamieDornan",
  JAMIE_HECTOR: "jamieHector",
  JANE_HARPER: "Jane Harper",
  JASON_BATEMAN: "jasonBateman",
  JEFF_LINDSAY: "jeffLindsay",
  JEFFERY_DEAVER: "jefferyDeaver",
  JENNIFER_CARPENTER: "jenniferCarpenter",
  JEREMY_BRETT: "jeremyBrett",
  JESSE_KELLERMAN: "jesseKellerman",
  JILL_SCOTT: "jillScott",
  JODIE_WHITTAKER: "jodieWhittaker",
  JOE_PESCI: "joePesci",
  JOHN_D_MACDONALD: "johnDMacdonald",
  JOHN_GRISHAM: "johnGrisham",
  JOHN_HART: "johnHart",
  JOHN_LESCROART: "johnLescroart",
  JOHN_NETTLES: "johnNettles",
  JOHN_SANDFORD: "johnSandford",
  JONATHAN_KELLERMAN: "jonathanKellerman",
  JO_NESBO: "joNesbo",
  JULIE_CLARK: "Julie Clark",
  KARIN_SLAUGHTER: "karinSlaughter",
  KATE_ATKINSON: "kateAtkinson",
  KATHY_REICHS: "kathyReichs",
  KENNETH_BRANAGH: "kennethBranagh",
  KENNETH_MORE: "kennethMore",
  KEN_STOTT: "kenStott",
  KIMBERLY_MCCREIGHT: "kimberlyMcCreight",
  KIM_NOVAK: "kimNovak",
  KINGSLEY_AMIS: "kingsleyAmis",
  LAURA_LINNEY: "lauraLinney",
  LAURA_LIPPMAN: "lauraLippman",
  LEE_CHILD: "Lee Child",
  LENA_OLIN: "lenaOlin",
  LIANE_MORIARTY: "lianeMoriarty",
  LINWOOD_BARCLAY: "linwoodBarclay",
  LISA_BLACK: "lisaBlack",
  LISA_JACKSON: "lisaJackson",
  LISA_JEWELL: "lisaJewell",
  LISA_SCOTTOLINE: "lisaScottoline",
  LISA_UNGER: "lisaUnger",
  LOUISE_PENNY: "louisePenny",
  LOUIS_HOFMANN: "louisHofmann",
  LUC_BESSON: "lucBesson",
  LUCY_FOLEY: "lucyFoley",
  MADS_MIKKELSEN: "madsMikkelsen",
  MARISA_TOMEI: "marisaTomei",
  MARK_NYKANEN: "markNykanen",
  MARK_WILLIAMS: "markWilliams",
  MARTHA_GRIMES: "Martha Grimes",
  MARTIN_SCORSESE: "martinScorsese",
  MARY_KUBICA: "maryKubica",
  MATT_BARR: "mattBarr",
  MATTHEW_MCCONAUGHEY: "matthewMcConaughey",
  MAVIS_DORIEL_HAY: "mavisDorielHay",
  MC_BEATON: "mcBeaton",
  MEGAN_GOLDIN: "Megan Goldin",
  MEG_GARDINER: "megGardiner",
  MICHAEL_CAINE: "michaelCaine",
  MICHAEL_CHABON: "michaelChabon",
  MICHAEL_C_HALL: "michaelCHall",
  MICHAEL_CONNELLY: "Michael Connelly",
  MICHELE_SCOTT: "micheleScott",
  MICHELLE_DOCKERY: "michelleDockery",
  MIM_EICHMANN: "Mim Eichmann",
  NATHANIEL_PARKER: "nathanielParker",
  NEIL_DUDGEON: "neilDudgeon",
  NGAIO_MARSH: "ngaioMarsh",
  NICCI_FRENCH: "nicciFrench",
  NINA_GEORGE: "ninaGeorge",
  NINA_SIMON: "Nina Simon",
  NITA_PROSE: "Nita Prose",
  OLIVIA_COLMAN: "oliviaColman",
  OWEN_LAUKKANEN: "owenLaukkanen",
  PATRICIA_CLARKSON: "patriciaClarkson",
  PATRICIA_HIGHSMITH: "patriciaHighsmith",
  PAULINE_COLLINS: "paulineCollins",
  PENELOPE_CRUZ: "penelopeCruz",
  PENN_BADGLEY: "pennBadgley",
  PETER_MOSS: "peterMoss",
  PETER_SWANSON: "peterSwanson",
  RAYMOND_CHANDLER: "raymondChandler",
  RIAN_JOHNSON: "rianJohnson",
  RICHARD_ARMITAGE: "richardArmitage",
  RICHARD_HARRINGTON: "richardHarrington",
  RICHARD_OSMAN: "Richard Osman",
  RILEY_SAGER: "Riley Sager",
  ROBBIE_COLTRANE: "robbieColtrane",
  ROBERT_CRAIS: "robertCrais",
  ROBERT_DE_NIRO: "robertDeNiro",
  ROBERT_GALBRAITH: "robertGalbraith",
  ROBERT_WALKER: "robertWalker",
  ROBSON_GREEN: "robsonGreen",
  ROGER_HOBBS: "rogerHobbs",
  ROSAMUND_PIKE: "rosamundPike",
  RUTH_WARE: "Ruth Ware",
  SALLY_WAINWRIGHT: "sallyWainwright",
  SAM_RAIMI: "samRaimi",
  SANDRA_BROWN: "sandraBrown",
  SARAH_LANCASHIRE: "sarahLancashire",
  SARAH_PEARSE: "Sarah Pearse",
  SCOTT_B_SMITH: "scottBSmith",
  SCOTT_TUROW: "scottTurow",
  SC_LALLI: "S.C. Lalli",
  SHARI_LAPENA: "shariLapena",
  SIDNEY_LUMET: "sidneyLumet",
  SIMON_BECKETT: "simonBeckett",
  SIMON_BRETT: "simonBrett",
  SOPHIE_HANNAH: "sophieHannah",
  STEPHEN_J_CANNELL: "stephenJCannell",
  STEPHEN_WHITE: "stephenWhite",
  STIEG_LARSSON: "stiegLarsson",
  STUART_WOODS: "stuartWoods",
  SURANNE_JONES: "suranneJones",
  SW_KANE: "S.W. Kane",
  TANA_FRENCH: "tanaFrench",
  TED_DEKKER: "tedDekker",
  TESS_GERRITSEN: "tessGerritsen",
  THOMAS_HARRIS: "thomasHarris",
  TITUS_WELLIVER: "titusWelliver",
  TOM_CONTI: "tomConti",
  TOM_CRUISE: "tomCruise",
  TUPPENCE_MIDDLETON: "tuppenceMiddleton",
  WILLIAM_LANDAY: "williamLanday",
  WILLY_RUSSELL: "willyRussell",
};

Person.properties = {
  [Person.AGATHA_CHRISTIE]: {
    first: "Agatha",
    last: "Christie",
    gr: "author/show/123715.Agatha_Christie",
    imdb: "name/nm0002005",
    lt: "author/christieagatha",
    wiki: "Agatha_Christie",
  },
  [Person.ALEXANDRA_BENEDICT]: {
    first: "Alexandra",
    last: "Benedict",
    gr: "author/show/22307202.Alexandra_Benedict",
    lt: "author/benedictalexandra",
  },
  [Person.ALICE_FEENEY]: {
    first: "Alice",
    last: "Feeney",
    gr: "author/show/15904689.Alice_Feeney",
    lt: "author/feeneyalice",
  },
  [Person.AMY_TINTERA]: {
    first: "Amy",
    last: "Tintera",
    gr: "author/show/5768611.Amy_Tintera",
    lt: "author/tinteraamy",
  },
  [Person.ANDREW_CHILD]: {
    first: "Andrew",
    last: "Child",
    gr: "author/show/19939004.Andrew_Child",
  },
  [Person.ANTHONY_HOROWITZ]: {
    first: "Anthony",
    last: "Horowitz",
    gr: "author/show/32590.Anthony_Horowitz",
    imdb: "name/nm0395275",
    lt: "author/horowitzanthony",
    wiki: "Anthony_Horowitz",
  },
  [Person.BENJAMIN_STEVENSON]: {
    first: "Benjamin",
    last: "Stevenson",
    gr: "author/show/18206333.Benjamin_Stevenson",
  },
  [Person.FABIAN_NICIEZA]: {
    first: "Fabian",
    last: "Nicieza",
    gr: "author/show/28126.Fabian_Nicieza",
    lt: "author/niciezafabian",
  },
  [Person.GK_CHESTERTON]: {
    first: "G.",
    middle: "K.",
    last: "Chesterton",
    gr: "author/show/7014283.G_K_Chesterton",
    imdb: "name/nm0156363",
    lt: "author/chestertongk",
    wiki: "G._K._Chesterton",
  },
  [Person.HARLAN_COBEN]: {
    first: "Harlan",
    last: "Coben",
    gr: "author/show/24689.Harlan_Coben",
    imdb: "name/nm1454192",
    lt: "author/cobenharlan",
    wiki: "Harlan_Coben",
  },
  [Person.JANE_HARPER]: {
    first: "Jane",
    last: "Harper",
    gr: "author/show/556546.Jane_Harper",
    imdb: "name/nm7681091",
    lt: "author/harperjane-1",
    wiki: "Jane_Harper",
  },
  [Person.JULIE_CLARK]: {
    first: "Julie",
    last: "Clark",
    gr: "author/show/17323560.Julie_Clark",
    lt: "author/clarkjulie-5",
  },
  [Person.LEE_CHILD]: {
    first: "Lee",
    last: "Child",
    gr: "author/show/5091.Lee_Child",
    imdb: "name/nm1676193",
    lt: "author/childlee",
    wiki: "Lee_Child",
  },
  [Person.MARTHA_GRIMES]: {
    first: "Martha",
    last: "Grimes",
    gr: "author/show/14150.Martha_Grimes",
    lt: "author/grimesmartha",
    wiki: "Martha_Grimes",
  },
  [Person.MEGAN_GOLDIN]: {
    first: "Megan",
    last: "Goldin",
    gr: "author/show/16718134.Megan_Goldin",
    lt: "author/goldinmegan",
  },
  [Person.MICHAEL_CONNELLY]: {
    first: "Michael",
    last: "Connelly",
    gr: "author/show/12470.Michael_Connelly",
    imdb: "name/nm0175093",
    lt: "author/connellymichael-1",
    wiki: "Michael_Connelly",
  },
  [Person.MIM_EICHMANN]: {
    first: "Mim",
    last: "Eichmann",
    gr: "author/show/19987913.Mim_Eichmann",
    lt: "author/eichmannmim",
  },
  [Person.NINA_SIMON]: {
    first: "Nina",
    last: "Simon",
    gr: "author/show/3408558.Nina_Simon",
    lt: "author/simonnina",
  },
  [Person.NITA_PROSE]: {
    first: "Nita",
    last: "Prose",
    gr: "author/show/20650250.Nita_Prose",
    lt: "author/prosenita",
  },
  [Person.RICHARD_OSMAN]: {
    first: "Richard",
    last: "Osman",
    gr: "author/show/6173710.Richard_Osman",
    imdb: "name/nm0652066",
    lt: "author/osmanrichard",
    wiki: "Richard_Osman",
  },
  [Person.RILEY_SAGER]: {
    first: "Riley",
    last: "Sager",
    gr: "author/show/15263414.Riley_Sager",
    lt: "author/sagerriley",
    wiki: "Riley_Sager",
  },
  [Person.RUTH_WARE]: {
    first: "Ruth",
    last: "Ware",
    gr: "author/show/9013543.Ruth_Ware",
    imdb: "name/nm3405121",
    lt: "author/wareruth",
    wiki: "Ruth_Ware",
  },
  [Person.SARAH_PEARSE]: {
    first: "Sarah",
    last: "Pearse",
    gr: "author/show/20458083.Sarah_Pearse",
    lt: "author/pearsesarah",
  },
  [Person.SC_LALLI]: {
    first: "S.",
    middle: "C.",
    last: "Lalli",
    gr: "author/show/21804660.S_C_Lalli",
    lt: "author/lallisc",
  },
  [Person.SW_KANE]: {
    first: "S.",
    middle: "W.",
    last: "Kane",
    gr: "author/show/19227228.S_W_Kane",
    lt: "author/kanesw",
  },
  aaMilne: {
    first: "A.",
    middle: "A.",
    last: "Milne",
    imdb: "name/nm0590316",
    lt: "author/milneaa",
    wiki: "A._A._Milne",
  },
  ajFinn: {
    first: "A.J.",
    last: "Finn",
    wiki: "A._J._Finn",
  },
  alPacino: {
    first: "Al",
    last: "Pacino",
    imdb: "name/nm0000199",
    wiki: "Al_Pacino",
  },
  alanBradley: {
    first: "Alan",
    last: "Bradley",
    wiki: "Alan_Bradley_(writer)",
  },
  alexMarwood: {
    first: "Alex",
    last: "Marwood",
    wiki: "Serena_Mackesy",
  },
  alexMichaelides: {
    first: "Alex",
    last: "Michaelides",
    gr: "author/show/17621440.Alex_Michaelides",
    imdb: "name/nm1955863",
    lt: "author/michaelidesalex",
    wiki: "Alex_Michaelides",
  },
  alexPavesi: {
    first: "Alex",
    last: "Pavesi",
    gr: "author/show/19623359.Alex_Pavesi",
    lt: "author/pavesialex",
  },
  alexanderMcCallSmith: {
    first: "Alexander",
    middle: "McCall",
    last: "Smith",
    gr: "author/show/4738.Alexander_McCall_Smith",
    imdb: "name/nm1676691",
    lt: "author/mccallsmithalexander",
    wiki: "Alexander_McCall_Smith",
  },
  alfredHitchcock: {
    first: "Alfred",
    last: "Hitchcock",
    imdb: "name/nm0000033",
  },
  aliceBlanchard: {
    first: "Alice",
    last: "Blanchard",
    lt: "author/blanchardalice",
    wiki: "Alice_Blanchard",
  },
  allanCubitt: {
    first: "Allan",
    last: "Cubitt",
    imdb: "name/nm0190930",
  },
  amyAdams: {
    first: "Amy",
    last: "Adams",
    imdb: "name/nm0010736",
  },
  annaFriel: {
    first: "Anna",
    last: "Friel",
    imdb: "name/nm0295484",
    wiki: "Anna_Friel",
  },
  anthonyBerkeleyCox: {
    first: "Anthony",
    middle: "Berkeley",
    last: "Cox",
    imdb: "name/nm0075324",
    lt: "author/berkeleyanthony",
    wiki: "Anthony_Berkeley_Cox",
  },
  arthurConanDoyle: {
    first: "Arthur",
    middle: "Conan",
    last: "Doyle",
    imdb: "name/nm0236279",
    lt: "author/doylearthurconan",
    wiki: "Arthur_Conan_Doyle",
  },
  baParis: {
    first: "B.A.",
    last: "Paris",
    lt: "author/parisba",
  },
  barbaraNickless: {
    first: "Barbara",
    last: "Nickless",
    gr: "author/show/1362211.Barbara_Nickless",
    lt: "author/nicklessbarbara",
  },
  barbaraStanwyck: {
    first: "Barbara",
    last: "Stanwyck",
    imdb: "name/nm0001766",
  },
  barbaraVine: {
    first: "Barbara",
    last: "Vine",
    gr: "author/show/47687.Barbara_Vine",
    lt: "author/vinebarbara",
    wiki: "Ruth_Rendell",
  },
  benAffleck: {
    first: "Ben",
    last: "Affleck",
    imdb: "name/nm0000255",
    wiki: "Ben_Affleck",
  },
  bertieCarvel: {
    first: "Bertie",
    last: "Carvel",
    imdb: "name/nm1584487",
  },
  billPaxton: {
    first: "Bill",
    last: "Paxton",
    imdb: "name/nm0000200",
  },
  billyBobThornton: {
    first: "Billy",
    middle: "Bob",
    last: "Thornton",
    imdb: "name/nm0000671",
  },
  billyWilder: {
    first: "Billy",
    last: "Wilder",
    imdb: "name/nm0000697",
  },
  boileauNarcejac: {
    last: "Boileau-Narcejac",
    gr: "author/show/81479.Boileau_Narcejac",
    lt: "author/boileaunarcejac",
  },
  bridgetFonda: {
    first: "Bridget",
    last: "Fonda",
    imdb: "name/nm0000403",
    wiki: "Bridget_Fonda",
  },
  carolineGraham: {
    first: "Caroline",
    last: "Graham",
    imdb: "name/nm0333956",
    lt: "author/grahamcaroline-1",
    wiki: "Caroline_Graham",
  },
  carolineKepnes: {
    first: "Caroline",
    last: "Kepnes",
    gr: "author/show/202260.Caroline_Kepnes",
    imdb: "name/nm2538919",
    lt: "author/kepnescaroline",
    wiki: "Caroline_Kepnes",
  },
  cazFrear: {
    first: "Caz",
    last: "Frear",
    lt: "author/frearcaz",
  },
  charlesBrandt: {
    first: "Charles",
    last: "Brandt",
    gr: "author/show/144064.Charles_Brandt",
    lt: "author/brandtcharles",
    wiki: "Charles_Brandt",
  },
  charlesTodd: {
    first: "Charles",
    last: "Todd",
    wiki: "Caroline_and_Charles_Todd",
  },
  chbKitchin: {
    first: "C.H.B.",
    last: "Kitchin",
    gr: "author/show/512327.C_H_B_Kitchin",
    lt: "author/kitchinchb",
    wiki: "C._H._B._Kitchin",
  },
  chelseaCain: {
    first: "Chelsea",
    last: "Cain",
    imdb: "name/nm4296249",
    lt: "author/cainchelsea",
    wiki: "Chelsea_Cain",
  },
  chevyStevens: {
    first: "Chevy",
    last: "Stevens",
    wiki: "Chevy_Stevens",
  },
  chrisChibnall: {
    first: "Chris",
    last: "Chibnall",
    gr: "author/show/8345740.Chris_Chibnall",
    imdb: "name/nm1163823",
    wiki: "Chris_Chibnall",
  },
  chrisEvans: {
    first: "Chris",
    last: "Evans",
    imdb: "name/nm0262635",
    wiki: "Chris_Evans_(actor)",
  },
  chrisPavone: {
    first: "Chris",
    last: "Pavone",
    imdb: "name/nm4949595",
    lt: "author/pavonechris",
    wiki: "Chris_Pavone",
  },
  christopherMoore: {
    first: "Christopher",
    last: "Moore",
    wiki: "Christopher_Moore_(author)",
  },
  christopherReeve: {
    first: "Christopher",
    last: "Reeve",
    imdb: "name/nm0001659",
  },
  cillianMurphy: {
    first: "Cillian",
    last: "Murphy",
    imdb: "name/nm0614165",
    wiki: "Cillian_Murphy",
  },
  cjBox: {
    first: "C.J.",
    last: "Box",
    imdb: "name/nm11353819",
    lt: "author/boxcj",
    wiki: "C._J._Box",
  },
  clareMackintosh: {
    first: "Clare",
    last: "Mackintosh",
    wiki: "Clare_Mackintosh",
  },
  cobieSmulders: {
    first: "Cobie",
    last: "Smulders",
    imdb: "name/nm1130627",
    wiki: "Cobie_Smulders",
  },
  cyrilCoke: {
    first: "Cyril",
    last: "Coke",
    imdb: "name/nm0170058",
  },
  danielCraig: {
    first: "Daniel",
    last: "Craig",
    imdb: "name/nm0185819",
    wiki: "Daniel_Craig",
  },
  danielSilva: {
    first: "Daniel",
    last: "Silva",
    lt: "author/silvadaniel",
    wiki: "Daniel_Silva_(novelist)",
  },
  dashiellHammett: {
    first: "Dashiell",
    last: "Hammett",
    lt: "author/hammettdashiell",
    wiki: "Dashiell_Hammett",
  },
  davidBaldacci: {
    first: "David",
    last: "Baldacci",
    imdb: "name/nm0049641",
    lt: "author/baldaccidavid",
    wiki: "David_Baldacci",
  },
  davidBurke: {
    first: "David",
    last: "Burke",
    imdb: "name/nm0121651",
    wiki: "David_Burke_(British_actor)",
  },
  davidRosenfelt: {
    first: "David",
    last: "Rosenfelt",
    wiki: "David_Rosenfelt",
  },
  davidSuchet: {
    first: "David",
    last: "Suchet",
    imdb: "name/nm0837064",
    wiki: "David_Suchet",
  },
  davidTennant: {
    first: "David",
    last: "Tennant",
    imdb: "name/nm0855039",
    wiki: "David_Tennant",
  },
  dawnFrench: {
    first: "Dawn",
    last: "French",
    imdb: "name/nm0294067",
  },
  deanKoontz: {
    first: "Dean",
    last: "Koontz",
    wiki: "Dean_Koontz",
  },
  deliaOwens: {
    first: "Delia",
    last: "Owens",
    lt: "author/owensdelia",
    wiki: "Delia_Owens",
  },
  dennisLehane: {
    first: "Dennis",
    last: "Lehane",
    wiki: "Dennis_Lehane",
  },
  dominicSmith: {
    first: "Dominic",
    last: "Smith",
    wiki: "Dominic_Smith_(author)",
  },
  donaldEWestlake: {
    first: "Donald",
    middle: "E.",
    last: "Westlake",
    gr: "author/show/30953.Donald_E_Westlake",
    lt: "author/westlakedonalde",
  },
  donnaTartt: {
    first: "Donna",
    last: "Tartt",
    imdb: "name/nm1535570",
    lt: "author/tarttdonna",
    wiki: "Donna_Tartt",
  },
  ednaBuchanan: {
    first: "Edna",
    last: "Buchanan",
    wiki: "Edna_Buchanan",
  },
  edwardGRobinson: {
    first: "Edward",
    middle: "G.",
    last: "Robinson",
    imdb: "name/nm0000064",
  },
  edwardHardwicke: {
    first: "Edward",
    last: "Hardwicke",
    imdb: "name/nm0362570",
    wiki: "Edward_Hardwicke",
  },
  elleryQueen: {
    first: "Ellery",
    last: "Queen",
    wiki: "Ellery_Queen",
  },
  emelieSchepp: {
    first: "Emelie",
    last: "Schepp",
    wiki: "Emelie_Schepp",
  },
  ericBana: {
    first: "Eric",
    last: "Bana",
    imdb: "name/nm0051509",
    wiki: "Eric_Bana",
  },
  erinKelly: {
    first: "Erin",
    last: "Kelly",
    gr: "author/show/1308914.Erin_Kelly",
    lt: "author/kellyerin-1",
  },
  ethelLinaWhite: {
    first: "Ethel",
    middle: "Lina",
    last: "White",
    gr: "author/show/11217.Ethel_Lina_White",
    imdb: "name/nm0924781",
    lt: "author/whiteethellina",
    wiki: "Ethel_Lina_White",
  },
  farleyGranger: {
    first: "Farley",
    last: "Granger",
    imdb: "name/nm0335048",
  },
  fredMacmurray: {
    first: "Fred",
    last: "MacMurray",
    imdb: "name/nm0534045",
  },
  gabrielByrne: {
    first: "Gabriel",
    last: "Byrne",
    imdb: "name/nm0000321",
    wiki: "Gabriel_Byrne",
  },
  genevieveOReilly: {
    first: "Genevieve",
    last: "O'Reilly",
    imdb: "name/nm0642444",
    wiki: "Genevieve_O%27Reilly",
  },
  georgetteHeyer: {
    first: "Georgette",
    last: "Heyer",
    wiki: "Georgette_Heyer",
  },
  gillianAnderson: {
    first: "Gillian",
    last: "Anderson",
    imdb: "name/nm0000096",
  },
  gillianFlynn: {
    first: "Gillian",
    last: "Flynn",
    imdb: "name/nm5058839",
    lt: "author/flynngillian",
    wiki: "Gillian_Flynn",
  },
  gregBerlanti: {
    first: "Greg",
    last: "Berlanti",
    imdb: "name/nm0075528",
    wiki: "Greg_Berlanti",
  },
  gregIles: {
    first: "Greg",
    last: "Iles",
    lt: "author/ilesgreg",
    wiki: "Greg_Iles",
  },
  greggHurwitz: {
    first: "Gregg",
    last: "Hurwitz",
    lt: "author/hurwitzgregg",
    wiki: "Gregg_Hurwitz",
  },
  hansRosenfeldt: {
    first: "Hans",
    last: "Rosenfeldt",
    imdb: "name/nm0742577",
    wiki: "Hans_Rosenfeldt",
  },
  harveyKeitel: {
    first: "Harvey",
    last: "Keitel",
    imdb: "name/nm0000172",
    wiki: "Harvey_Keitel",
  },
  hughDancy: {
    first: "Hugh",
    last: "Dancy",
    imdb: "name/nm0199215",
    wiki: "Hugh_Dancy",
  },
  hughFraser: {
    first: "Hugh",
    last: "Fraser",
    imdb: "name/nm0292140",
    wiki: "Hugh_Fraser_(actor)",
  },
  hywelBennett: {
    first: "Hywel",
    last: "Bennett",
    imdb: "name/nm0071799",
  },
  ianRankin: {
    first: "Ian",
    last: "Rankin",
    gr: "author/show/33031.Ian_Rankin",
    imdb: "name/nm0710256",
    lt: "author/rankinian",
    wiki: "Ian_Rankin",
  },
  iraLevin: {
    first: "Ira",
    last: "Levin",
    imdb: "name/nm0505615",
    lt: "author/levinira",
    wiki: "Ira_Levin",
  },
  jamesMCain: {
    first: "James",
    middle: "M.",
    last: "Cain",
    imdb: "name/nm0128906",
    lt: "author/cainjamesm",
    wiki: "James_M._Cain",
  },
  jamesNorton: {
    first: "James",
    last: "Norton",
    imdb: "name/nm3584268",
  },
  jamesOakley: {
    first: "James",
    last: "Oakley",
    imdb: "name/nm1950060",
  },
  jamesPatterson: {
    first: "James",
    last: "Patterson",
    imdb: "name/nm0666248",
    lt: "author/pattersonjames-1",
    wiki: "James_Patterson",
  },
  jamesStewart: {
    first: "James",
    last: "Stewart",
    imdb: "name/nm0000071",
    wiki: "James_Stewart",
  },
  jamieDornan: {
    first: "Jamie",
    last: "Dornan",
    imdb: "name/nm1946193",
  },
  jamieHector: {
    first: "Jamie",
    last: "Hector",
    imdb: "name/nm0373100",
    wiki: "Jamie_Hector",
  },
  jasonBateman: {
    first: "Jason",
    last: "Bateman",
    imdb: "name/nm0000867",
    wiki: "Jason_Bateman",
  },
  jeffLindsay: {
    first: "Jeff",
    last: "Lindsay",
    imdb: "name/nm2416255",
    lt: "author/lindsayjeff",
    wiki: "Jeff_Lindsay_(writer)",
  },
  jefferyDeaver: {
    first: "Jeffery",
    last: "Deaver",
    wiki: "Jeffery_Deaver",
  },
  jenniferCarpenter: {
    first: "Jennifer",
    last: "Carpenter",
    imdb: "name/nm1358539",
  },
  jeremyBrett: {
    first: "Jeremy",
    last: "Brett",
    imdb: "name/nm0107950",
    wiki: "Jeremy_Brett",
  },
  jesseKellerman: {
    first: "Jesse",
    last: "Kellerman",
    lt: "author/kellermanjesse",
  },
  jillScott: {
    first: "Jill",
    last: "Scott",
    imdb: "name/nm0779325",
  },
  joNesbo: {
    first: "Jo",
    last: "Nesbø",
    imdb: "name/nm1867674",
    lt: "author/nesbojo",
    wiki: "Jo_Nesbø",
  },
  jodieWhittaker: {
    first: "Jodie",
    last: "Whittaker",
    imdb: "name/nm2092886",
    wiki: "Jodie_Whittaker",
  },
  joePesci: {
    first: "Joe",
    last: "Pesci",
    imdb: "name/nm0000582",
    wiki: "Joe_Pesci",
  },
  johnDMacdonald: {
    first: "John",
    middle: "D.",
    last: "MacDonald",
    imdb: "name/nm0531792",
    lt: "author/macdonaldjohnd",
    wiki: "John_D._MacDonald",
  },
  johnGrisham: {
    first: "John",
    last: "Grisham",
    gr: "author/show/721.John_Grisham",
    imdb: "name/nm0001300",
    lt: "author/grishamjohn",
    wiki: "John_Grisham",
  },
  johnHart: {
    first: "John",
    last: "Hart",
    lt: "author/hartjohn-1",
    wiki: "John_Hart_(author)",
  },
  johnLescroart: {
    first: "John",
    last: "Lescroart",
    lt: "author/lescroartjohn",
    wiki: "John_Lescroart",
  },
  johnNettles: {
    first: "John",
    last: "Nettles",
    imdb: "name/nm0626719",
  },
  johnSandford: {
    first: "John",
    last: "Sandford",
    imdb: "name/nm0761859",
    lt: "author/sandfordjohn-1",
    wiki: "John_Sandford_(novelist)",
  },
  jonathanKellerman: {
    first: "Jonathan",
    last: "Kellerman",
    imdb: "name/nm0445814",
    lt: "author/kellermanjonathan",
    wiki: "Jonathan_Kellerman",
  },
  karinSlaughter: {
    first: "Karin",
    last: "Slaughter",
    imdb: "name/nm4901740",
    lt: "author/slaughterkarin",
    wiki: "Karin_Slaughter",
  },
  kateAtkinson: {
    first: "Kate",
    last: "Atkinson",
    wiki: "Kate_Atkinson",
  },
  kathyReichs: {
    first: "Kathy",
    last: "Reichs",
    wiki: "Kathy_Reichs",
  },
  kenStott: {
    first: "Ken",
    last: "Stott",
    imdb: "name/nm0832792",
  },
  kennethBranagh: {
    first: "Kenneth",
    last: "Branagh",
    imdb: "name/nm0000110",
    wiki: "Kenneth_Branagh",
  },
  kennethMore: {
    first: "Kenneth",
    last: "More",
    imdb: "name/nm0603336",
  },
  kimNovak: {
    first: "Kim",
    last: "Novak",
    imdb: "name/nm0001571",
    wiki: "Kim_Novak",
  },
  kimberlyMcCreight: {
    first: "Kimberly",
    last: "McCreight",
    wiki: "Kimberly_McCreight",
  },
  kingsleyAmis: {
    first: "Kingsley",
    last: "Amis",
    gr: "author/show/13078.Kingsley_Amis",
    imdb: "name/nm0025006",
    lt: "author/amiskingsley",
    wiki: "Kingsley_Amis",
  },
  lauraLinney: {
    first: "Laura",
    last: "Linney",
    imdb: "name/nm0001473",
    wiki: "Laura_Linney",
  },
  lauraLippman: {
    first: "Laura",
    last: "Lippman",
    imdb: "name/nm2887908",
    lt: "author/lippmanlaura-1",
    wiki: "Laura_Lippman",
  },
  lenaOlin: {
    first: "Lena",
    last: "Olin",
    imdb: "name/nm0000565",
    wiki: "Lena_Olin",
  },
  lianeMoriarty: {
    first: "Liane",
    last: "Moriarty",
    gr: "author/show/322069.Liane_Moriarty",
    lt: "author/moriartyliane",
    wiki: "Liane_Moriarty",
  },
  linwoodBarclay: {
    first: "Linwood",
    last: "Barclay",
    wiki: "Linwood_Barclay",
  },
  lisaBlack: {
    first: "Lisa",
    last: "Black",
    lt: "author/blacklisa-1",
  },
  lisaJackson: {
    first: "Lisa",
    last: "Jackson",
    wiki: "Lisa_Jackson_(author)",
  },
  lisaJewell: {
    first: "Lisa",
    last: "Jewell",
    gr: "author/show/93504.Lisa_Jewell",
    lt: "author/jewelllisa",
    wiki: "Lisa_Jewell",
  },
  lisaScottoline: {
    first: "Lisa",
    last: "Scottoline",
    wiki: "Lisa_Scottoline",
  },
  lisaUnger: {
    first: "Lisa",
    last: "Unger",
    gr: "author/show/18445.Lisa_Unger",
    lt: "author/ungerlisa",
    wiki: "Lisa_Unger",
  },
  louisHofmann: {
    first: "Louis",
    last: "Hofmann",
    imdb: "name/nm3836977",
  },
  louisePenny: {
    first: "Louise",
    last: "Penny",
    imdb: "name/nm5123910",
    lt: "author/pennylouise",
    wiki: "Louise_Penny",
  },
  lucBesson: {
    first: "Luc",
    last: "Besson",
    imdb: "name/nm0000108",
    wiki: "Luc_Besson",
  },
  lucyFoley: {
    first: "Lucy",
    last: "Foley",
    gr: "author/show/7770523.Lucy_Foley",
    lt: "author/foleylucy",
  },
  madsMikkelsen: {
    first: "Mads",
    last: "Mikkelsen",
    imdb: "name/nm0586568",
    wiki: "Mads_Mikkelsen",
  },
  marisaTomei: {
    first: "Marisa",
    last: "Tomei",
    imdb: "name/nm0000673",
    wiki: "Marisa_Tomei",
  },
  markNykanen: {
    first: "Mark",
    last: "Nykanen",
    lt: "author/nykanenmark",
    wiki: "Mark_Nykanen",
  },
  markWilliams: {
    first: "Mark",
    last: "Williams",
    imdb: "name/nm0931247",
  },
  martinScorsese: {
    first: "Martin",
    last: "Scorsese",
    imdb: "name/nm0000217",
  },
  maryKubica: {
    first: "Mary",
    last: "Kubica",
    lt: "author/kubicamary",
  },
  mattBarr: {
    first: "Matt",
    last: "Barr",
    imdb: "name/nm1204778",
  },
  matthewMcConaughey: {
    first: "Matthew",
    last: "McConaughey",
    imdb: "name/nm0000190",
    wiki: "Matthew_McConaughey",
  },
  mavisDorielHay: {
    first: "Mavis",
    middle: "Doriel",
    last: "Hay",
    lt: "author/haymavisdoriel",
    wiki: "Mavis_Doriel_Hay",
  },
  mcBeaton: {
    first: "M.C.",
    last: "Beaton",
    gr: "author/show/1657638.M_C_Beaton",
    lt: "author/beatonmc",
    wiki: "Marion_Chesney",
  },
  megGardiner: {
    first: "Meg",
    last: "Gardiner",
    imdb: "name/nm3125172",
    lt: "author/gardinermeg",
    wiki: "Meg_Gardiner",
  },
  michaelCHall: {
    first: "Michael",
    middle: "C.",
    last: "Hall",
    imdb: "name/nm0355910",
  },
  michaelCaine: {
    first: "Michael",
    last: "Caine",
    imdb: "name/nm0000323",
  },
  michaelChabon: {
    first: "Michael",
    last: "Chabon",
    lt: "author/chabonmichael",
    wiki: "Michael_Chabon",
  },
  micheleScott: {
    first: "Michele",
    last: "Scott",
    lt: "author/scottmichele-1",
  },
  michelleDockery: {
    first: "Michelle",
    last: "Dockery",
    imdb: "name/nm1890784",
  },
  nathanielParker: {
    first: "Nathaniel",
    last: "Parker",
    imdb: "name/nm0662511",
  },
  neilDudgeon: {
    first: "Neil",
    last: "Dudgeon",
    imdb: "name/nm0240072",
  },
  ngaioMarsh: {
    first: "Ngaio",
    last: "Marsh",
    lt: "author/marshngaio",
    wiki: "Ngaio_Marsh",
  },
  nicciFrench: {
    first: "Nicci",
    last: "French",
    lt: "author/frenchnicci",
    wiki: "Nicci_French",
  },
  ninaGeorge: {
    first: "Nina",
    last: "George",
    gr: "author/show/695300.Nina_George",
    lt: "author/georgenina",
    wiki: "Nina_George",
  },
  oliviaColman: {
    first: "Olivia",
    last: "Colman",
    imdb: "name/nm1469236",
    wiki: "Olivia_Colman",
  },
  owenLaukkanen: {
    first: "Owen",
    last: "Laukkanen",
    wiki: "Owen_Laukkanen",
  },
  patriciaClarkson: {
    first: "Patricia",
    last: "Clarkson",
    imdb: "name/nm0165101",
  },
  patriciaHighsmith: {
    first: "Patricia",
    last: "Highsmith",
    imdb: "name/nm0383604",
    lt: "author/highsmithpatricia",
    wiki: "Patricia_Highsmith",
  },
  paulineCollins: {
    first: "Pauline",
    last: "Collins",
    gr: "author/show/694522.Pauline_Collins",
    imdb: "name/nm0172604",
    lt: "author/collinspauline",
    wiki: "Pauline_Collins",
  },
  penelopeCruz: {
    first: "Penélope",
    last: "Cruz",
    imdb: "name/nm0004851",
    wiki: "Penélope_Cruz",
  },
  pennBadgley: {
    first: "Penn",
    last: "Badgley",
    imdb: "name/nm0046112",
  },
  peterMoss: {
    first: "Peter",
    last: "Moss",
    imdb: "name/nm0609062",
  },
  peterSwanson: {
    first: "Peter",
    last: "Swanson",
    gr: "author/show/7142445.Peter_Swanson",
    lt: "author/swansonpeter-1",
    wiki: "Peter_Swanson",
  },
  raymondChandler: {
    first: "Raymond",
    last: "Chandler",
    imdb: "name/nm0151452",
    lt: "author/chandlerraymond-1",
    wiki: "Raymond_Chandler",
  },
  rianJohnson: {
    first: "Rian",
    last: "Johnson",
    imdb: "name/nm0426059",
  },
  richardArmitage: {
    first: "Richard",
    last: "Armitage",
    imdb: "name/nm0035514",
  },
  richardHarrington: {
    first: "Richard",
    last: "Harrington",
    imdb: "name/nm0364348",
  },
  robbieColtrane: {
    first: "Robbie",
    last: "Coltrane",
    imdb: "name/nm0001059",
  },
  robertCrais: {
    first: "Robert",
    last: "Crais",
    gr: "author/show/8944.Robert_Crais",
    imdb: "name/nm0186101",
    lt: "author/craisrobert",
    wiki: "Robert_Crais",
  },
  robertDeNiro: {
    first: "Robert",
    last: "De Niro",
    imdb: "name/nm0000134",
    wiki: "Robert_De_Niro",
  },
  robertGalbraith: {
    first: "Robert",
    last: "Galbraith",
    lt: "author/galbraithrobert-1",
    wiki: "J._K._Rowling#Cormoran_Strike",
  },
  robertWalker: {
    first: "Robert",
    last: "Walker",
    imdb: "name/nm0908153",
  },
  robsonGreen: {
    first: "Robson",
    last: "Green",
    imdb: "name/nm0338292",
  },
  rogerHobbs: {
    first: "Roger",
    last: "Hobbs",
    lt: "author/hobbsroger",
    wiki: "Roger_Hobbs",
  },
  rosamundPike: {
    first: "Rosamund",
    last: "Pike",
    imdb: "name/nm0683253",
    wiki: "Rosamund_Pike",
  },
  sallyWainwright: {
    first: "Sally",
    last: "Wainwright",
    imdb: "name/nm0906550",
  },
  samRaimi: {
    first: "Sam",
    last: "Raimi",
    imdb: "name/nm0000600",
  },
  sandraBrown: {
    first: "Sandra",
    last: "Brown",
    wiki: "Sandra_Brown",
  },
  sarahLancashire: {
    first: "Sarah",
    last: "Lancashire",
    imdb: "name/nm0484104",
  },
  scottBSmith: {
    first: "Scott",
    middle: "B.",
    last: "Smith",
    gr: "author/show/12505.Scott_B_Smith",
    imdb: "name/nm0809895",
    lt: "author/smithscott-1",
    wiki: "Scott_Smith_(author)",
  },
  scottTurow: {
    first: "Scott",
    last: "Turow",
    gr: "author/show/2749.Scott_Turow",
    lt: "author/turowscott",
    wiki: "Scott_Turow",
  },
  shariLapena: {
    first: "Shari",
    last: "Lapena",
    wiki: "Shari_Lapena",
  },
  sidneyLumet: {
    first: "Sidney",
    last: "Lumet",
    imdb: "name/nm0001486",
  },
  simonBeckett: {
    first: "Simon",
    last: "Beckett",
    lt: "author/beckettsimon",
    wiki: "Simon_Beckett",
  },
  simonBrett: {
    first: "Simon",
    last: "Brett",
    lt: "author/brettsimon-1",
    wiki: "Simon_Brett",
  },
  sophieHannah: {
    first: "Sophie",
    last: "Hannah",
    gr: "author/show/232473.Sophie_Hannah",
    lt: "author/hannahsophie",
    wiki: "Sophie_Hannah",
  },
  stephenJCannell: {
    first: "Stephen",
    middle: "J.",
    last: "Cannell",
    imdb: "name/nm0004798",
    wiki: "Stephen_J._Cannell",
  },
  stephenWhite: {
    first: "Stephen",
    last: "White",
    wiki: "Stephen_White_(author)",
  },
  stiegLarsson: {
    first: "Stieg",
    last: "Larsson",
    imdb: "name/nm2297183",
    lt: "author/larssonstieg",
    wiki: "Stieg_Larsson",
  },
  stuartWoods: {
    first: "Stuart",
    last: "Woods",
    wiki: "Stuart_Woods",
  },
  suranneJones: {
    first: "Suranne",
    last: "Jones",
    imdb: "name/nm1013087",
  },
  tanaFrench: {
    first: "Tana",
    last: "French",
    lt: "author/frenchtana",
    wiki: "Tana_French",
  },
  tedDekker: {
    first: "Ted",
    last: "Dekker",
    wiki: "Ted_Dekker",
  },
  tessGerritsen: {
    first: "Tess",
    last: "Gerritsen",
    imdb: "name/nm2446740",
    lt: "author/gerritsentess",
    wiki: "Tess_Gerritsen",
  },
  thomasHarris: {
    first: "Thomas",
    last: "Harris",
    gr: "author/show/12455.Thomas_Harris",
    imdb: "name/nm0365383",
    lt: "author/harristhomas-1",
    wiki: "Thomas_Harris",
  },
  titusWelliver: {
    first: "Titus",
    last: "Welliver",
    imdb: "name/nm0920038",
    wiki: "Titus_Welliver",
  },
  tomConti: {
    first: "Tom",
    last: "Conti",
    imdb: "name/nm0002018",
    wiki: "Tom_Conti",
  },
  tomCruise: {
    first: "Tom",
    last: "Cruise",
    imdb: "name/nm0000129",
    wiki: "Tom_Cruise",
  },
  tuppenceMiddleton: {
    first: "Tuppence",
    last: "Middleton",
    imdb: "name/nm3095562",
  },
  williamLanday: {
    first: "William",
    last: "Landay",
    wiki: "William_Landay",
  },
  willyRussell: {
    first: "Willy",
    last: "Russell",
    gr: "author/show/22987.Willy_Russell",
    imdb: "name/nm0751516",
    lt: "author/russellwilly",
    wiki: "Willy_Russell",
  },
};

Person.keys = () => Object.keys(Person.properties);

Person.values = () => Object.values(Person.properties);

{
  const forEachFunction = (key) => {
    const value = Person.properties[key];

    if (R.isNil(value.key)) {
      value.key = key;
    }
  };
  R.forEach(forEachFunction, Person.keys());
}

Object.freeze(Person);

module.exports = Person;
